//! Targeted FFI surface tests that fill the residual line/branch coverage gaps
//! left by `ffi_snapshot.rs`. Every test exercises the public `mosaic_uniffi`
//! re-exports — the FFI scaffolding generated by `uniffi::setup_scaffolding!`
//! is intentionally untested because it can only execute under the UniFFI
//! runtime, not in native Rust integration tests.

use mosaic_client::ClientErrorCode;
use mosaic_crypto::{KdfProfile, MIN_KDF_ITERATIONS, MIN_KDF_MEMORY_KIB, derive_account_key};
use mosaic_uniffi::{
    AccountUnlockRequest, ClientCoreAlbumSyncEvent, ClientCoreAlbumSyncRequest,
    ClientCoreAlbumSyncSnapshot, ClientCoreUploadJobEvent, ClientCoreUploadJobRequest,
    ClientCoreUploadJobSnapshot, ClientCoreUploadShardRef, advance_album_sync, advance_upload_job,
    canonical_media_metadata_sidecar_bytes, canonical_metadata_sidecar_bytes,
    close_account_key_handle, close_epoch_key_handle, crate_name, create_epoch_key_handle,
    init_album_sync, init_upload_job, inspect_media_image, parse_envelope_header,
    plan_media_tier_layout, unlock_account_key,
};
use zeroize::Zeroizing;

const PASSWORD: &[u8] = b"correct horse battery staple";
const USER_SALT: [u8; 16] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
];
const ACCOUNT_SALT: [u8; 16] = [
    0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff,
];
const PNG_SIGNATURE: &[u8; 8] = b"\x89PNG\r\n\x1a\n";
const JOB_ID: &str = "018f0000-0000-7000-8000-000000000101";
const ALBUM_ID: &str = "018f0000-0000-7000-8000-000000000102";
const ASSET_ID: &str = "018f0000-0000-7000-8000-000000000103";
const IDEMPOTENCY_KEY: &str = "018f0000-0000-7000-8000-000000000104";
const EFFECT_ID: &str = "018f0000-0000-7000-8000-000000000105";
const SHARD_ID: &str = "018f0000-0000-7000-8000-000000000106";

// ---------------------------------------------------------------------------
// crate_name() smoke test — non-uniffi const fn that exists for diagnostics.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_facade_exposes_crate_name_for_wrapper_diagnostics() {
    assert_eq!(crate_name(), "mosaic-uniffi");
}

// ---------------------------------------------------------------------------
// parse_envelope_header error paths — drives ClientErrorCode::Invalid* codes
// through the FFI surface.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_parse_envelope_header_rejects_short_bytes() {
    let result = parse_envelope_header(Vec::new());
    assert_eq!(result.code, ClientErrorCode::InvalidHeaderLength.as_u16());
    assert_eq!(result.epoch_id, 0);
    assert_eq!(result.shard_index, 0);
    assert_eq!(result.tier, 0);
    assert!(result.nonce.is_empty());
}

#[test]
fn uniffi_parse_envelope_header_rejects_bad_magic() {
    // 64 bytes that look like a header but do not start with the magic prefix.
    let bytes = vec![0_u8; 64];
    let result = parse_envelope_header(bytes);
    assert_eq!(result.code, ClientErrorCode::InvalidMagic.as_u16());
    assert!(result.nonce.is_empty());
}

// ---------------------------------------------------------------------------
// Phase string lookup coverage. Each iteration exercises one arm of
// `upload_phase_from_string` / `album_sync_phase_from_string`. We do not
// assert on the resulting `code`: the SM may reject the synthetic snapshot
// for reasons unrelated to the FFI's phase lookup (e.g. ApplyingPage requires
// `current_page` which the DTO cannot carry; UploadingShard requires a
// pending `shard_id`). The coverage we care about — the matching arm
// inside `*_phase_from_string` — has already executed by the time
// `advance_*` returns, so a non-panicking call is enough.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_advance_upload_job_accepts_every_known_phase_string() {
    for phase in [
        "Queued",
        "AwaitingPreparedMedia",
        "AwaitingEpochHandle",
        "EncryptingShard",
        "CreatingShardUpload",
        "UploadingShard",
        "CreatingManifest",
        "ManifestCommitUnknown",
        "AwaitingSyncConfirmation",
        "RetryWaiting",
        "Confirmed",
        "Cancelled",
        "Failed",
    ] {
        let mut snapshot = baseline_upload_snapshot();
        snapshot.phase = phase.to_owned();
        let _ = advance_upload_job(snapshot, upload_event("CancelRequested", 0, 0, 0));
    }
}

#[test]
fn uniffi_advance_album_sync_accepts_every_known_phase_string() {
    for phase in [
        "Idle",
        "FetchingPage",
        "ApplyingPage",
        "RetryWaiting",
        "Completed",
        "Cancelled",
        "Failed",
    ] {
        let mut snapshot = baseline_album_sync_snapshot();
        snapshot.phase = phase.to_owned();
        let _ = advance_album_sync(snapshot, album_sync_event("CancelRequested", 0));
    }
}

// ---------------------------------------------------------------------------
// last_error_stage lookup coverage. Same coverage rationale as the phase
// tests above: the lookup runs during `*_snapshot_to_client`, even when the
// state machine ultimately rejects the snapshot.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_advance_album_sync_accepts_every_known_last_error_stage() {
    for stage in [
        "Idle",
        "FetchingPage",
        "ApplyingPage",
        "RetryWaiting",
        "Completed",
        "Cancelled",
        "Failed",
    ] {
        let mut snapshot = retry_waiting_album_sync_snapshot();
        stage.clone_into(&mut snapshot.last_error_stage);
        let _ = advance_album_sync(snapshot, album_sync_event("RetryTimerElapsed", 0));
    }
}

// ---------------------------------------------------------------------------
// last_error_code lookup coverage — exercises every Some-arm of
// `client_error_code_from_u16` by feeding each known code through the
// `last_error_code` field. As above, we exercise the lookup itself; the
// SM is free to reject the synthetic snapshot afterwards.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_advance_album_sync_accepts_every_known_client_error_code() {
    for code in known_client_error_codes() {
        let mut snapshot = retry_waiting_album_sync_snapshot();
        snapshot.last_error_code = *code;
        let _ = advance_album_sync(snapshot, album_sync_event("RetryTimerElapsed", 0));
    }
}

// ---------------------------------------------------------------------------
// Event-kind lookup coverage — exercises every arm of `upload_event_to_client`.
// Includes the two-name aliases ("PreparedMedia", "EpochHandleReady") and the
// unknown-kind branch that maps to ClientCoreInvalidTransition.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_advance_upload_job_accepts_every_known_event_kind() {
    for kind in [
        "StartRequested",
        "Start",
        "MediaPrepared",
        "PreparedMedia",
        "EpochHandleAcquired",
        "EpochHandleReady",
        "ShardEncrypted",
        "ShardUploadCreated",
        "ShardUploaded",
        "ManifestCreated",
        "ManifestOutcomeUnknown",
        "SyncConfirmed",
        "RetryableFailure",
        "RetryTimerElapsed",
        "CancelRequested",
        "NonRetryableFailure",
    ] {
        let snapshot = baseline_upload_snapshot();
        let mut event = upload_event(kind, 7, 0, 0);
        if kind == "RetryableFailure" || kind == "NonRetryableFailure" {
            event.error_code = ClientErrorCode::AuthenticationFailed.as_u16();
            event.has_error_code = true;
        }
        let _ = advance_upload_job(snapshot, event);
    }
}

#[test]
fn uniffi_advance_upload_job_unknown_event_kind_returns_invalid_transition() {
    let snapshot = baseline_upload_snapshot();
    let result = advance_upload_job(snapshot, upload_event("DefinitelyNotAKind", 0, 0, 0));
    assert_eq!(
        result.code,
        ClientErrorCode::ClientCoreInvalidTransition.as_u16()
    );
    assert!(result.transition.effects.is_empty());
}

#[test]
fn uniffi_advance_album_sync_accepts_every_known_event_kind() {
    for kind in [
        "SyncRequested",
        "StartRequested",
        "Start",
        "PageFetched",
        "PageApplied",
        "RetryableFailure",
        "RetryTimerElapsed",
        "CancelRequested",
        "NonRetryableFailure",
    ] {
        let snapshot = baseline_album_sync_snapshot();
        let mut event = album_sync_event(kind, 0);
        if kind == "RetryableFailure" || kind == "NonRetryableFailure" {
            event.error_code = ClientErrorCode::AuthenticationFailed.as_u16();
            event.has_error_code = true;
        }
        let _ = advance_album_sync(snapshot, event);
    }
}

#[test]
fn uniffi_advance_album_sync_unknown_event_kind_returns_invalid_transition() {
    let snapshot = baseline_album_sync_snapshot();
    let result = advance_album_sync(snapshot, album_sync_event("DefinitelyNotAKind", 0));
    assert_eq!(
        result.code,
        ClientErrorCode::ClientCoreInvalidTransition.as_u16()
    );
    assert!(result.transition.effects.is_empty());
}

#[test]
fn uniffi_advance_album_sync_sync_requested_uses_event_cursor_when_present() {
    // Drives the `if event.fetched_cursor.is_empty() { "sync" } else { event.fetched_cursor }`
    // branch in album_sync_event_to_client when fetched_cursor is non-empty.
    let snapshot = baseline_album_sync_snapshot();
    let mut event = album_sync_event("SyncRequested", 0);
    "explicit-sync-id".clone_into(&mut event.fetched_cursor);
    "next-cursor-token".clone_into(&mut event.next_cursor);
    let _ = advance_album_sync(snapshot, event);
}

#[test]
fn uniffi_advance_album_sync_page_fetched_with_non_empty_next_cursor() {
    // Drives both branches of `reached_end: event.next_cursor.is_empty()` in
    // PageFetched mapping by using a non-empty next_cursor. The SM may still
    // reject for token-mismatch reasons; the FFI mapping arm is what we want.
    let snapshot = baseline_album_sync_snapshot();
    let mut event = album_sync_event("PageFetched", 0);
    event.applied_count = 3;
    "next-page".clone_into(&mut event.next_cursor);
    let _ = advance_album_sync(snapshot, event);
}

#[test]
fn uniffi_advance_album_sync_retryable_failure_with_retry_after_unix_ms() {
    let snapshot = baseline_album_sync_snapshot();
    let mut event = album_sync_event("RetryableFailure", 0);
    event.error_code = ClientErrorCode::AuthenticationFailed.as_u16();
    event.has_error_code = true;
    event.retry_after_unix_ms = 1_700_000_999_000;
    let _ = advance_album_sync(snapshot, event);
}

#[test]
fn uniffi_upload_event_rejects_error_code_without_presence_flag() {
    let snapshot = baseline_upload_snapshot();
    let mut event = upload_event(
        "NonRetryableFailure",
        0,
        0,
        ClientErrorCode::AuthenticationFailed.as_u16(),
    );
    event.has_error_code = false;

    let result = advance_upload_job(snapshot, event);

    assert_eq!(
        result.code,
        ClientErrorCode::ClientCoreInvalidSnapshot.as_u16()
    );
}

#[test]
fn uniffi_upload_failure_event_rejects_present_zero_error_code() {
    let snapshot = baseline_upload_snapshot();
    let mut event = upload_event("NonRetryableFailure", 0, 0, 0);
    event.has_error_code = true;

    let result = advance_upload_job(snapshot, event);

    assert_eq!(
        result.code,
        ClientErrorCode::ClientCoreInvalidSnapshot.as_u16()
    );
}

#[test]
fn uniffi_upload_shard_event_rejects_uploaded_flag_kind_mismatch() {
    let snapshot = baseline_upload_snapshot();
    let mut event = upload_event("ShardEncrypted", 0, 0, 0);
    event.uploaded = true;

    let result = advance_upload_job(snapshot, event);

    assert_eq!(
        result.code,
        ClientErrorCode::ClientCoreInvalidTransition.as_u16()
    );
}

// ---------------------------------------------------------------------------
// upload_active_slot EncryptingShard branch. A snapshot whose phase is
// EncryptingShard with no pending shard but two completed shards forces the
// FFI mapping to fall through to the planned-shards lookup. Non-empty
// shard_ids are required so validate_safe_text accepts the snapshot.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_init_upload_job_returns_queued_snapshot_on_success() {
    let request = ClientCoreUploadJobRequest {
        job_id: JOB_ID.to_owned(),
        album_id: ALBUM_ID.to_owned(),
        asset_id: ASSET_ID.to_owned(),
        idempotency_key: IDEMPOTENCY_KEY.to_owned(),
        max_retry_count: 5,
    };
    let result = init_upload_job(request);
    assert_eq!(result.code, ClientErrorCode::Ok.as_u16());
    assert_eq!(result.snapshot.job_id, JOB_ID);
    assert_eq!(result.snapshot.album_id, ALBUM_ID);
    assert_eq!(result.snapshot.idempotency_key, IDEMPOTENCY_KEY);
    assert_eq!(result.snapshot.phase, "Queued");
    assert_eq!(result.snapshot.max_retry_count, 5);
}

#[test]
fn uniffi_init_album_sync_returns_idle_snapshot_on_success() {
    let request = ClientCoreAlbumSyncRequest {
        request_id: "req-init".to_owned(),
        album_id: "album-init-sync".to_owned(),
        start_cursor: String::new(),
        now_unix_ms: 1_700_000_000_000,
        max_retry_count: 5,
    };
    let result = init_album_sync(request);
    assert_eq!(result.code, ClientErrorCode::Ok.as_u16());
    assert_eq!(result.snapshot.album_id, "album-init-sync");
    assert_eq!(result.snapshot.phase, "Idle");
    assert_eq!(result.snapshot.max_retry_count, 5);
}

#[test]
fn uniffi_init_album_sync_carries_start_cursor_into_active_cursor() {
    let request = ClientCoreAlbumSyncRequest {
        request_id: "req-cursor".to_owned(),
        album_id: "album-init-sync-cursor".to_owned(),
        start_cursor: "page-token-1".to_owned(),
        now_unix_ms: 1_700_000_000_000,
        max_retry_count: 3,
    };
    let result = init_album_sync(request);
    assert_eq!(result.code, ClientErrorCode::Ok.as_u16());
    assert_eq!(result.snapshot.active_cursor, "page-token-1");
}

#[test]
fn uniffi_init_upload_job_rejects_empty_album_id_with_stable_code() {
    let request = ClientCoreUploadJobRequest {
        job_id: JOB_ID.to_owned(),
        album_id: String::new(),
        asset_id: ASSET_ID.to_owned(),
        idempotency_key: IDEMPOTENCY_KEY.to_owned(),
        max_retry_count: 5,
    };
    let result = init_upload_job(request);
    // The SM rejects empty album/idempotency key with a stable client
    // error code; the FFI must surface that without panicking.
    assert_ne!(result.code, ClientErrorCode::Ok.as_u16());
    assert_eq!(result.snapshot.album_id, "");
    assert_eq!(result.snapshot.phase, "");
}

// ---------------------------------------------------------------------------
// Driving a real upload-job flow exercises every variant of
// upload_effect_from_client. Because the DTO does not preserve
// `planned_shards`, we manually re-inject `active_tier` / `active_shard_index`
// between transitions when needed; otherwise the round-trip would lose the
// shard slot the SM expects to see.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_advance_album_sync_emits_fetch_and_apply_page_effects() {
    let init = init_album_sync(ClientCoreAlbumSyncRequest {
        request_id: "req-flow".to_owned(),
        album_id: "album-flow".to_owned(),
        start_cursor: String::new(),
        now_unix_ms: 1_700_000_000_000,
        max_retry_count: 5,
    });
    assert_eq!(init.code, 0);
    let mut snapshot = init.snapshot;
    let mut effects_seen = Vec::<String>::new();

    // SyncRequested → FetchPage
    let result = advance_album_sync(snapshot, album_sync_event("SyncRequested", 0));
    assert_eq!(result.code, 0);
    record_album_sync_effects(&result, &mut effects_seen);
    snapshot = result.transition.snapshot;

    // PageFetched → ApplyPage
    let mut event = album_sync_event("PageFetched", 0);
    "page-token-2".clone_into(&mut event.next_cursor);
    event.applied_count = 4;
    let result = advance_album_sync(snapshot, event);
    assert_eq!(result.code, 0);
    record_album_sync_effects(&result, &mut effects_seen);

    assert!(
        effects_seen.iter().any(|kind| kind == "FetchPage"),
        "expected FetchPage effect, observed = {effects_seen:?}"
    );
    assert!(
        effects_seen.iter().any(|kind| kind == "ApplyPage"),
        "expected ApplyPage effect, observed = {effects_seen:?}"
    );
}

#[test]
fn uniffi_advance_album_sync_emits_schedule_retry_effect_on_retryable_failure() {
    // Construct a snapshot directly in FetchingPage with max_retry_count=5
    // so RetryableFailure produces a ScheduleRetry effect rather than a
    // budget-exhausted Failed transition.
    let snapshot = ClientCoreAlbumSyncSnapshot {
        schema_version: 1,
        album_id: "album-retry-direct".to_owned(),
        phase: "FetchingPage".to_owned(),
        active_cursor: String::new(),
        pending_cursor: String::new(),
        rerun_requested: false,
        retry_count: 0,
        max_retry_count: 5,
        next_retry_unix_ms: 0,
        last_error_code: 0,
        last_error_stage: String::new(),
        updated_at_unix_ms: 0,
    };
    let mut event = album_sync_event("RetryableFailure", 0);
    event.error_code = ClientErrorCode::AuthenticationFailed.as_u16();
    event.has_error_code = true;
    event.retry_after_unix_ms = 1_700_000_009_000;
    let result = advance_album_sync(snapshot, event);
    assert_eq!(result.code, 0);
    let kinds: Vec<&str> = result
        .transition
        .effects
        .iter()
        .map(|effect| effect.kind.as_str())
        .collect();
    assert!(
        kinds.iter().any(|kind| kind.starts_with("ScheduleRetry:")),
        "expected ScheduleRetry effect, observed = {kinds:?}"
    );
    assert_eq!(result.transition.snapshot.phase, "RetryWaiting");
}

// ---------------------------------------------------------------------------
// inspect_media_image / map_media_error — drive UnsupportedFormat,
// InvalidPng, InvalidJpeg, InvalidWebP, InvalidDimensions, plus the
// JPEG and WebP success arms of media_format_name.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_inspect_media_image_returns_invalid_png_on_truncated_signature() {
    let mut bytes = PNG_SIGNATURE.to_vec();
    bytes.extend_from_slice(&[0_u8; 2]);
    let result = inspect_media_image(bytes);
    assert_eq!(result.code, ClientErrorCode::InvalidMediaContainer.as_u16());
    assert_eq!(result.format, "");
}

#[test]
fn uniffi_inspect_media_image_returns_invalid_jpeg_on_truncated_jpeg() {
    let bytes = vec![0xff, 0xd8];
    let result = inspect_media_image(bytes);
    assert_eq!(result.code, ClientErrorCode::InvalidMediaContainer.as_u16());
}

#[test]
fn uniffi_inspect_media_image_returns_invalid_webp_on_truncated_riff() {
    let mut bytes = b"RIFF".to_vec();
    bytes.extend_from_slice(&[0, 0, 0, 0]);
    bytes.extend_from_slice(b"WEBP");
    let result = inspect_media_image(bytes);
    assert_eq!(result.code, ClientErrorCode::InvalidMediaContainer.as_u16());
}

#[test]
fn uniffi_inspect_media_image_recognizes_minimal_jpeg_with_sof0() {
    // SOI + SOF0 segment (precision 8, height 4, width 8, components 1).
    let bytes = vec![
        0xff, 0xd8, 0xff, 0xc0, 0x00, 0x0b, 0x08, 0x00, 0x04, 0x00, 0x08, 0x01, 0x01, 0x11, 0x00,
    ];
    let result = inspect_media_image(bytes);
    assert_eq!(result.code, 0);
    assert_eq!(result.format, "jpeg");
    assert_eq!(result.mime_type, "image/jpeg");
    assert_eq!(result.width, 8);
    assert_eq!(result.height, 4);
}

#[test]
fn uniffi_inspect_media_image_recognizes_minimal_webp_vp8l() {
    let payload = build_webp_vp8l(10, 6);
    let result = inspect_media_image(payload);
    assert_eq!(result.code, 0);
    assert_eq!(result.format, "webp");
    assert_eq!(result.mime_type, "image/webp");
    assert_eq!(result.width, 10);
    assert_eq!(result.height, 6);
}

#[test]
fn uniffi_canonical_media_metadata_sidecar_bytes_propagates_invalid_uuid_length() {
    let result = canonical_media_metadata_sidecar_bytes(
        vec![0x11; 8],
        [0x22; 16].to_vec(),
        7,
        png_bytes(64, 32),
    );
    assert_eq!(result.code, ClientErrorCode::InvalidInputLength.as_u16());
    assert!(result.bytes.is_empty());
}

#[test]
fn uniffi_canonical_metadata_sidecar_bytes_rejects_invalid_album_uuid() {
    let result =
        canonical_metadata_sidecar_bytes(vec![0x11; 15], [0x22; 16].to_vec(), 4, Vec::new());
    assert_eq!(result.code, ClientErrorCode::InvalidInputLength.as_u16());
    assert!(result.bytes.is_empty());
}

#[test]
fn uniffi_canonical_metadata_sidecar_bytes_rejects_truncated_field_payload() {
    // A field that declares value_len=4 but only supplies 2 bytes triggers
    // the `end > encoded_fields.len()` rejection inside
    // metadata_fields_from_encoded.
    let mut encoded = Vec::new();
    encoded.extend_from_slice(&7_u16.to_le_bytes());
    encoded.extend_from_slice(&4_u32.to_le_bytes());
    encoded.extend_from_slice(&[0xab, 0xcd]);
    let result =
        canonical_metadata_sidecar_bytes([0x11; 16].to_vec(), [0x22; 16].to_vec(), 9, encoded);
    assert_eq!(result.code, ClientErrorCode::InvalidInputLength.as_u16());
    assert!(result.bytes.is_empty());
}

#[test]
fn uniffi_plan_media_tier_layout_zero_height_returns_invalid_dimensions() {
    let result = plan_media_tier_layout(1024, 0);
    assert_eq!(
        result.code,
        ClientErrorCode::InvalidMediaDimensions.as_u16()
    );
    assert_eq!(result.thumbnail.width, 0);
    assert_eq!(result.thumbnail.height, 0);
}

// ---------------------------------------------------------------------------
// Account/epoch handle close idempotency — closes a freshly created
// account+epoch handle pair twice each and asserts the second close hits
// the dedicated not-found error mapping path.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_account_and_epoch_handles_close_idempotently_after_explicit_close() {
    let unlock = unlock_account_key(PASSWORD.to_vec(), unlock_request(wrapped_account_key()));
    assert_eq!(unlock.code, 0);
    assert_ne!(unlock.handle, 0);

    let epoch = create_epoch_key_handle(unlock.handle, 99);
    assert_eq!(epoch.code, 0);
    assert_ne!(epoch.handle, 0);

    assert_eq!(close_epoch_key_handle(epoch.handle), 0);
    assert_eq!(
        close_epoch_key_handle(epoch.handle),
        ClientErrorCode::EpochHandleNotFound.as_u16()
    );
    assert_eq!(close_account_key_handle(unlock.handle), 0);
    assert_eq!(
        close_account_key_handle(unlock.handle),
        ClientErrorCode::SecretHandleNotFound.as_u16()
    );
}

// ---------------------------------------------------------------------------
// Test helpers (duplicated locally because each integration test file is its
// own crate compilation unit).
// ---------------------------------------------------------------------------

fn known_client_error_codes() -> &'static [u16] {
    // Mirrors every Some(_) arm of `client_error_code_from_u16` in lib.rs.
    &[
        0, 100, 101, 102, 103, 104, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
        212, 213, 214, 300, 400, 401, 402, 403, 500, 600, 601, 602, 603, 604, 605, 606, 700, 701,
        702, 703, 704, 705, 706,
    ]
}

fn record_album_sync_effects(
    result: &mosaic_uniffi::ClientCoreAlbumSyncTransitionResult,
    out: &mut Vec<String>,
) {
    for effect in &result.transition.effects {
        out.push(effect.kind.clone());
    }
}

fn baseline_upload_snapshot() -> ClientCoreUploadJobSnapshot {
    ClientCoreUploadJobSnapshot {
        schema_version: 1,
        job_id: JOB_ID.to_owned(),
        album_id: ALBUM_ID.to_owned(),
        phase: "Queued".to_owned(),
        retry_count: 0,
        max_retry_count: 5,
        next_retry_not_before_ms: 0,
        has_next_retry_not_before_ms: false,
        idempotency_key: IDEMPOTENCY_KEY.to_owned(),
        tiered_shards: vec![upload_shard(false)],
        shard_set_hash: vec![0x22; 32],
        snapshot_revision: 0,
        last_effect_id: String::new(),
        last_acknowledged_effect_id: String::new(),
        last_applied_event_id: String::new(),
        failure_code: 0,
    }
}

fn baseline_album_sync_snapshot() -> ClientCoreAlbumSyncSnapshot {
    ClientCoreAlbumSyncSnapshot {
        schema_version: 1,
        album_id: "album-baseline-sync".to_owned(),
        phase: "Idle".to_owned(),
        active_cursor: String::new(),
        pending_cursor: String::new(),
        rerun_requested: false,
        retry_count: 0,
        max_retry_count: 5,
        next_retry_unix_ms: 0,
        last_error_code: 0,
        last_error_stage: String::new(),
        updated_at_unix_ms: 0,
    }
}

fn upload_shard(uploaded: bool) -> ClientCoreUploadShardRef {
    ClientCoreUploadShardRef {
        tier: 3,
        shard_index: 0,
        shard_id: SHARD_ID.to_owned(),
        sha256: vec![0x11; 32],
        content_length: 1024,
        envelope_version: 3,
        uploaded,
    }
}

fn retry_waiting_album_sync_snapshot() -> ClientCoreAlbumSyncSnapshot {
    ClientCoreAlbumSyncSnapshot {
        schema_version: 1,
        album_id: "album-retry-sync".to_owned(),
        phase: "RetryWaiting".to_owned(),
        active_cursor: "cursor".to_owned(),
        pending_cursor: String::new(),
        rerun_requested: false,
        retry_count: 1,
        max_retry_count: 5,
        next_retry_unix_ms: 1_700_000_020_000,
        last_error_code: ClientErrorCode::InvalidInputLength.as_u16(),
        last_error_stage: "FetchingPage".to_owned(),
        updated_at_unix_ms: 1_700_000_020_000,
    }
}

fn upload_event(
    kind: &str,
    _epoch_id: u32,
    shard_index: u32,
    error_code: u16,
) -> ClientCoreUploadJobEvent {
    ClientCoreUploadJobEvent {
        kind: kind.to_owned(),
        effect_id: EFFECT_ID.to_owned(),
        tier: 3,
        shard_index,
        shard_id: SHARD_ID.to_owned(),
        sha256: vec![0x11; 32],
        content_length: 1024,
        envelope_version: 3,
        uploaded: kind == "ShardUploaded",
        tiered_shards: Vec::new(),
        shard_set_hash: vec![0x22; 32],
        asset_id: ASSET_ID.to_owned(),
        since_metadata_version: 0,
        recovery_outcome: "Match".to_owned(),
        now_ms: 1_700_000_020_000,
        base_backoff_ms: 1_000,
        server_retry_after_ms: 0,
        has_server_retry_after_ms: false,
        has_error_code: error_code != 0,
        error_code,
        target_phase: "CreatingShardUpload".to_owned(),
    }
}

fn album_sync_event(kind: &str, error_code: u16) -> ClientCoreAlbumSyncEvent {
    ClientCoreAlbumSyncEvent {
        kind: kind.to_owned(),
        fetched_cursor: String::new(),
        next_cursor: String::new(),
        applied_count: 0,
        observed_asset_ids: Vec::new(),
        retry_after_unix_ms: 0,
        has_error_code: error_code != 0,
        error_code,
    }
}

fn unlock_request(wrapped_account_key: Vec<u8>) -> AccountUnlockRequest {
    AccountUnlockRequest {
        user_salt: USER_SALT.to_vec(),
        account_salt: ACCOUNT_SALT.to_vec(),
        wrapped_account_key,
        kdf_memory_kib: MIN_KDF_MEMORY_KIB,
        kdf_iterations: MIN_KDF_ITERATIONS,
        kdf_parallelism: 1,
    }
}

fn wrapped_account_key() -> Vec<u8> {
    let profile = match KdfProfile::new(MIN_KDF_MEMORY_KIB, MIN_KDF_ITERATIONS, 1) {
        Ok(value) => value,
        Err(error) => panic!("minimum Mosaic profile should be valid: {error:?}"),
    };
    let material = match derive_account_key(
        Zeroizing::new(PASSWORD.to_vec()),
        &USER_SALT,
        &ACCOUNT_SALT,
        profile,
    ) {
        Ok(value) => value,
        Err(error) => panic!("account key should derive: {error:?}"),
    };
    material.wrapped_account_key
}

fn png_bytes(width: u32, height: u32) -> Vec<u8> {
    let mut bytes = PNG_SIGNATURE.to_vec();
    let mut ihdr = Vec::new();
    ihdr.extend_from_slice(&width.to_be_bytes());
    ihdr.extend_from_slice(&height.to_be_bytes());
    ihdr.extend_from_slice(&[8, 2, 0, 0, 0]);
    let payload_len = match u32::try_from(ihdr.len()) {
        Ok(value) => value,
        Err(error) => panic!("ihdr len should fit u32: {error:?}"),
    };
    bytes.extend_from_slice(&payload_len.to_be_bytes());
    bytes.extend_from_slice(b"IHDR");
    bytes.extend_from_slice(&ihdr);
    bytes.extend_from_slice(&[0, 0, 0, 0]);
    bytes
}

fn build_webp_vp8l(width: u32, height: u32) -> Vec<u8> {
    // VP8L (lossless WebP) encodes (width-1) and (height-1) into 14 bits each
    // following a 0x2f signature byte. We then wrap that chunk in the RIFF/WEBP
    // container the inspector expects.
    let w = (width - 1) & 0x3fff;
    let h = (height - 1) & 0x3fff;
    let bits: u32 = 0x2f | (w << 8) | (h << 22);
    let chunk_payload = vec![
        (bits & 0xff) as u8,
        ((bits >> 8) & 0xff) as u8,
        ((bits >> 16) & 0xff) as u8,
        ((bits >> 24) & 0xff) as u8,
        0, // alpha/version flags
    ];

    let mut bytes = Vec::with_capacity(12 + 8 + chunk_payload.len() + 1);
    bytes.extend_from_slice(b"RIFF");
    let payload_len = match u32::try_from(4 + 8 + chunk_payload.len()) {
        Ok(value) => value,
        Err(error) => panic!("riff len should fit u32: {error:?}"),
    };
    bytes.extend_from_slice(&payload_len.to_le_bytes());
    bytes.extend_from_slice(b"WEBP");
    bytes.extend_from_slice(b"VP8L");
    let chunk_len = match u32::try_from(chunk_payload.len()) {
        Ok(value) => value,
        Err(error) => panic!("vp8l len should fit u32: {error:?}"),
    };
    bytes.extend_from_slice(&chunk_len.to_le_bytes());
    bytes.extend_from_slice(&chunk_payload);
    if bytes.len() % 2 != 0 {
        bytes.push(0);
    }
    bytes
}

// ---------------------------------------------------------------------------
// Download orchestrator UniFFI edge-case coverage.
// ---------------------------------------------------------------------------

#[test]
fn uniffi_build_download_plan_accepts_empty_entries_and_returns_empty_plan_cbor_array() {
    use mosaic_uniffi::{DownloadPlanInput, build_download_plan};
    let result = build_download_plan(DownloadPlanInput {
        album_id: vec![0_u8; 16],
        entries: Vec::new(),
    });
    assert_eq!(result.code, ClientErrorCode::Ok.as_u16());
    assert!(result.error_detail.is_none());
    // An empty plan canonically encodes as a single byte CBOR empty array (0x80).
    assert_eq!(result.plan_cbor, vec![0x80]);
}

#[test]
fn uniffi_build_download_plan_rejects_photo_with_no_shards() {
    use mosaic_uniffi::{DownloadPlanEntryInput, DownloadPlanInput, build_download_plan};
    let result = build_download_plan(DownloadPlanInput {
        album_id: vec![0_u8; 16],
        entries: vec![DownloadPlanEntryInput {
            photo_id: "photo-empty".to_owned(),
            filename: "empty.jpg".to_owned(),
            shards: Vec::new(),
        }],
    });
    assert_eq!(result.code, ClientErrorCode::DownloadInvalidPlan.as_u16());
    let detail = result.error_detail.unwrap_or_default();
    assert!(
        detail.starts_with("PhotoHasNoShards:"),
        "expected PhotoHasNoShards, got {detail:?}"
    );
}

#[test]
fn uniffi_apply_download_event_rejects_zero_length_state_cbor() {
    use mosaic_uniffi::apply_download_event;
    let result = apply_download_event(Vec::new(), Vec::new());
    assert_eq!(
        result.code,
        ClientErrorCode::DownloadSnapshotCorrupt.as_u16()
    );
    assert!(result.new_state_cbor.is_empty());
}

#[test]
fn uniffi_load_download_snapshot_rejects_zero_length_snapshot_cbor() {
    use mosaic_uniffi::load_download_snapshot;
    let result = load_download_snapshot(Vec::new(), vec![0_u8; 32]);
    assert_eq!(
        result.code,
        ClientErrorCode::DownloadSnapshotChecksumMismatch.as_u16()
    );
}

#[test]
fn uniffi_commit_download_snapshot_rejects_garbage_bytes() {
    use mosaic_uniffi::commit_download_snapshot;
    let result = commit_download_snapshot(vec![0xff_u8, 0x00, 0xde, 0xad]);
    assert_eq!(
        result.code,
        ClientErrorCode::DownloadSnapshotCorrupt.as_u16()
    );
    assert!(result.body.is_empty());
    assert!(result.checksum.is_empty());
}

#[test]
fn uniffi_verify_download_snapshot_returns_ok_code_with_invalid_flag_for_empty_inputs() {
    use mosaic_uniffi::verify_download_snapshot;
    // Empty body with empty checksum: code is Ok (constant-time path), valid is false.
    let result = verify_download_snapshot(Vec::new(), Vec::new());
    assert_eq!(result.code, ClientErrorCode::Ok.as_u16());
    assert!(!result.valid);
}
