//! Gated media processing boundary crate for Mosaic.

#![forbid(unsafe_code)]

const PNG_SIGNATURE: &[u8; 8] = b"\x89PNG\r\n\x1a\n";
pub const NORMAL_EXIF_ORIENTATION: u8 = 1;
pub const MAX_IMAGE_PIXELS: u32 = 32 * 1024 * 1024;
/// Maximum canonical thumbnail tier edge length in pixels.
pub const THUMBNAIL_MAX_DIMENSION: u32 = 256;
/// Maximum canonical preview tier edge length in pixels.
pub const PREVIEW_MAX_DIMENSION: u32 = 1024;

/// Supported image container formats for dependency-free media boundary checks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MediaFormat {
    Jpeg,
    Png,
    WebP,
}

impl MediaFormat {
    /// Returns the canonical MIME type for this media format.
    #[must_use]
    pub const fn mime_type(self) -> &'static str {
        match self {
            Self::Jpeg => "image/jpeg",
            Self::Png => "image/png",
            Self::WebP => "image/webp",
        }
    }
}

/// Recognized metadata categories stripped from gallery tier bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MetadataKind {
    Exif,
    Xmp,
    Iptc,
    Comment,
    Text,
    Timestamp,
    ColorProfile,
    PhysicalDimensions,
    SuggestedPalette,
    RenderingHint,
}

/// Media processing errors.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MosaicMediaError {
    InvalidJpeg,
    InvalidPng,
    InvalidWebP,
    InvalidDimensions,
    UnsupportedFormat,
    OutputTooLarge,
    ImageMetadataMismatch,
    EncodedTierMismatch {
        expected: TierDimensions,
        actual: TierDimensions,
    },
}

/// Container-level image metadata needed before tier planning and encryption.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ImageMetadata {
    pub format: MediaFormat,
    pub mime_type: &'static str,
    pub width: u32,
    pub height: u32,
    pub orientation: u8,
}

/// Planned dimensions for one canonical shard tier.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TierDimensions {
    pub tier: mosaic_domain::ShardTier,
    pub width: u32,
    pub height: u32,
}

/// Canonical dependency-free layout for media tiers derived from display dimensions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TierLayout {
    pub thumbnail: TierDimensions,
    pub preview: TierDimensions,
    pub original: TierDimensions,
}

impl TierLayout {
    /// Returns tiers in canonical manifest/upload order.
    #[must_use]
    pub const fn tiers(&self) -> [TierDimensions; 3] {
        [self.thumbnail, self.preview, self.original]
    }
}

/// Generated bytes for one canonical gallery media tier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TierOutput {
    pub tier: mosaic_domain::ShardTier,
    pub width: u32,
    pub height: u32,
    pub bytes: Vec<u8>,
}

/// Generated gallery tiers in canonical manifest/upload order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTiers {
    tiers: [TierOutput; 3],
}

impl GeneratedTiers {
    /// Returns tiers in canonical thumbnail, preview, original order.
    #[must_use]
    pub const fn tiers(&self) -> &[TierOutput; 3] {
        &self.tiers
    }

    /// Consumes this result and returns the canonical tier array.
    #[must_use]
    pub fn into_tiers(self) -> [TierOutput; 3] {
        self.tiers
    }
}

/// Boundary implemented by future codec adapters to encode derived tiers.
///
/// Implementations receive sanitized source bytes plus the already-inspected
/// container metadata and requested dimensions. They must not use filenames,
/// captions, platform metadata, keys, filesystem/network state, or other side
/// channels, and they must return the requested tier identity and dimensions.
pub trait MediaTierEncoder {
    /// Encodes a single planned thumbnail or preview tier from sanitized source bytes.
    ///
    /// # Errors
    /// Returns a media error when the adapter cannot produce the requested tier.
    fn encode_tier(
        &self,
        source: &[u8],
        metadata: ImageMetadata,
        dimensions: TierDimensions,
    ) -> Result<TierOutput, MosaicMediaError>;
}

/// Result of stripping recognized metadata from an image container.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StrippedMedia {
    /// Media bytes with recognized metadata carriers removed.
    pub bytes: Vec<u8>,
    /// Metadata categories removed, in encounter order.
    pub removed: Vec<MetadataKind>,
}

/// Removes recognized metadata carriers from supported image containers.
///
/// This does not decode or transform pixels. It is the dependency-free first
/// gate for normalized gallery tiers before encryption: server-bound media bytes
/// must not carry EXIF/GPS, XMP, IPTC, comments, textual chunks, timestamps,
/// physical-resolution hints, suggested palettes, rendering hints, or embedded
/// color profiles unless explicitly re-embedded during a controlled export flow.
///
/// # Errors
/// Returns a format-specific error when container boundaries are malformed.
pub fn strip_known_metadata(
    format: MediaFormat,
    bytes: &[u8],
) -> Result<StrippedMedia, MosaicMediaError> {
    match format {
        MediaFormat::Jpeg => strip_jpeg_metadata(bytes),
        MediaFormat::Png => strip_png_metadata(bytes),
        MediaFormat::WebP => strip_webp_metadata(bytes),
    }
}

/// Inspects supported image bytes and returns dependency-free container metadata.
///
/// This reads only container headers. It does not decode pixels, allocate output
/// tiers, preserve metadata, or trust MIME labels supplied by the platform.
///
/// # Errors
/// Returns `UnsupportedFormat` if the magic bytes do not identify JPEG, PNG, or
/// WebP; otherwise returns a format-specific error for malformed/truncated
/// headers or `InvalidDimensions` for zero or out-of-budget dimensions.
pub fn inspect_image(bytes: &[u8]) -> Result<ImageMetadata, MosaicMediaError> {
    let format = detect_format(bytes)?;
    let (raw_width, raw_height) = match format {
        MediaFormat::Jpeg => inspect_jpeg_dimensions(bytes)?,
        MediaFormat::Png => inspect_png_dimensions(bytes)?,
        MediaFormat::WebP => inspect_webp_dimensions(bytes)?,
    };
    let orientation = extract_exif_orientation(format, bytes)?;
    let (width, height) = normalize_dimensions_by_orientation(raw_width, raw_height, orientation)?;

    Ok(ImageMetadata {
        format,
        mime_type: format.mime_type(),
        width,
        height,
        orientation,
    })
}

/// Generates canonical gallery tiers from original media bytes.
///
/// This dependency-free orchestration function inspects the source container,
/// strips recognized metadata, plans canonical tier dimensions, delegates only
/// thumbnail/preview encoding to the adapter, and assigns the stripped source
/// bytes to the original tier.
///
/// # Errors
/// Returns inspection, metadata stripping, layout planning, adapter, or adapter
/// output validation errors.
pub fn generate_tiers<E: MediaTierEncoder + ?Sized>(
    bytes: &[u8],
    encoder: &E,
) -> Result<GeneratedTiers, MosaicMediaError> {
    let metadata = inspect_image(bytes)?;
    generate_tiers_with_metadata(bytes, metadata, encoder)
}

/// Generates canonical gallery tiers using already-inspected image metadata.
///
/// Callers that already invoked [`inspect_image`] can pass the resulting
/// metadata. The metadata is re-checked against the source bytes to reject
/// stale or mismatched metadata before planning or encoding. The source bytes
/// are still stripped before any output tier is returned.
///
/// # Errors
/// Returns metadata stripping, layout planning, adapter, or adapter output
/// validation errors.
pub fn generate_tiers_with_metadata<E: MediaTierEncoder + ?Sized>(
    bytes: &[u8],
    metadata: ImageMetadata,
    encoder: &E,
) -> Result<GeneratedTiers, MosaicMediaError> {
    let actual_metadata = inspect_image(bytes)?;
    if actual_metadata != metadata {
        return Err(MosaicMediaError::ImageMetadataMismatch);
    }

    let stripped = strip_known_metadata(metadata.format, bytes)?;
    let layout = plan_tier_layout(metadata.width, metadata.height)?;

    let thumbnail = encode_and_validate_tier(encoder, &stripped.bytes, metadata, layout.thumbnail)?;
    let preview = encode_and_validate_tier(encoder, &stripped.bytes, metadata, layout.preview)?;
    let original = TierOutput {
        tier: layout.original.tier,
        width: layout.original.width,
        height: layout.original.height,
        bytes: stripped.bytes,
    };

    Ok(GeneratedTiers {
        tiers: [thumbnail, preview, original],
    })
}

/// Plans canonical thumbnail, preview, and original tier dimensions.
///
/// Inputs must already be normalized display dimensions, such as the `width`
/// and `height` returned by [`inspect_image`]. This function does not decode,
/// transform, encode, read, or write media bytes.
///
/// # Errors
/// Returns `InvalidDimensions` for zero or over-budget source dimensions.
pub fn plan_tier_layout(width: u32, height: u32) -> Result<TierLayout, MosaicMediaError> {
    let (width, height) = validate_dimensions(width, height)?;
    let (thumbnail_width, thumbnail_height) =
        fit_inside_square(width, height, THUMBNAIL_MAX_DIMENSION);
    let (preview_width, preview_height) = fit_inside_square(width, height, PREVIEW_MAX_DIMENSION);

    Ok(TierLayout {
        thumbnail: TierDimensions {
            tier: mosaic_domain::ShardTier::Thumbnail,
            width: thumbnail_width,
            height: thumbnail_height,
        },
        preview: TierDimensions {
            tier: mosaic_domain::ShardTier::Preview,
            width: preview_width,
            height: preview_height,
        },
        original: TierDimensions {
            tier: mosaic_domain::ShardTier::Original,
            width,
            height,
        },
    })
}

fn encode_and_validate_tier<E: MediaTierEncoder + ?Sized>(
    encoder: &E,
    source: &[u8],
    metadata: ImageMetadata,
    dimensions: TierDimensions,
) -> Result<TierOutput, MosaicMediaError> {
    let output = encoder.encode_tier(source, metadata, dimensions)?;
    let actual = TierDimensions {
        tier: output.tier,
        width: output.width,
        height: output.height,
    };
    if actual != dimensions {
        return Err(MosaicMediaError::EncodedTierMismatch {
            expected: dimensions,
            actual,
        });
    }

    Ok(output)
}

/// Extracts the canonical EXIF orientation value used for display normalization.
///
/// This slice parses JPEG APP1 EXIF TIFF IFD0 tag `0x0112`. Missing, malformed,
/// or out-of-range orientation metadata returns `1` because EXIF is optional and
/// stripped from gallery tier bytes. Malformed JPEG container boundaries still
/// return `InvalidJpeg`.
///
/// # Errors
/// Returns `InvalidJpeg` when JPEG marker boundaries are malformed.
pub fn extract_exif_orientation(format: MediaFormat, bytes: &[u8]) -> Result<u8, MosaicMediaError> {
    match format {
        MediaFormat::Jpeg => extract_jpeg_exif_orientation(bytes),
        MediaFormat::Png | MediaFormat::WebP => Ok(NORMAL_EXIF_ORIENTATION),
    }
}

/// Applies EXIF orientation display policy to container dimensions.
///
/// Orientations `5..=8` transpose the display dimensions. Unknown orientation
/// values are canonicalized to normal orientation to match EXIF fallback policy.
///
/// # Errors
/// Returns `InvalidDimensions` for zero or over-budget normalized dimensions.
pub fn normalize_dimensions_by_orientation(
    width: u32,
    height: u32,
    orientation: u8,
) -> Result<(u32, u32), MosaicMediaError> {
    if orientation_swaps_dimensions(canonical_exif_orientation(u16::from(orientation))) {
        return validate_dimensions(height, width);
    }

    validate_dimensions(width, height)
}

/// Returns the crate name for smoke tests and media prototype diagnostics.
#[must_use]
pub const fn crate_name() -> &'static str {
    "mosaic-media"
}

/// Returns the domain protocol version this media crate is compiled against.
#[must_use]
pub const fn protocol_version() -> &'static str {
    mosaic_domain::PROTOCOL_VERSION
}

fn detect_format(bytes: &[u8]) -> Result<MediaFormat, MosaicMediaError> {
    if bytes.starts_with(&[0xff, 0xd8]) {
        return Ok(MediaFormat::Jpeg);
    }
    if bytes.starts_with(PNG_SIGNATURE) {
        return Ok(MediaFormat::Png);
    }
    if bytes.len() >= 12 && bytes.starts_with(b"RIFF") && bytes.get(8..12) == Some(b"WEBP") {
        return Ok(MediaFormat::WebP);
    }
    Err(MosaicMediaError::UnsupportedFormat)
}

fn validate_dimensions(width: u32, height: u32) -> Result<(u32, u32), MosaicMediaError> {
    if width == 0 || height == 0 {
        return Err(MosaicMediaError::InvalidDimensions);
    }

    let pixels = u64::from(width) * u64::from(height);
    if pixels > u64::from(MAX_IMAGE_PIXELS) {
        return Err(MosaicMediaError::InvalidDimensions);
    }

    Ok((width, height))
}

fn fit_inside_square(width: u32, height: u32, max_dimension: u32) -> (u32, u32) {
    if width <= max_dimension && height <= max_dimension {
        return (width, height);
    }

    if width >= height {
        (
            max_dimension,
            scale_secondary_dimension(height, max_dimension, width),
        )
    } else {
        (
            scale_secondary_dimension(width, max_dimension, height),
            max_dimension,
        )
    }
}

fn scale_secondary_dimension(dimension: u32, max_dimension: u32, dominant_dimension: u32) -> u32 {
    let scaled = (u64::from(dimension) * u64::from(max_dimension)) / u64::from(dominant_dimension);
    match u32::try_from(scaled.clamp(1, u64::from(max_dimension))) {
        Ok(value) => value,
        Err(_) => max_dimension,
    }
}

fn extract_jpeg_exif_orientation(bytes: &[u8]) -> Result<u8, MosaicMediaError> {
    if !bytes.starts_with(&[0xff, 0xd8]) {
        return Err(MosaicMediaError::InvalidJpeg);
    }

    let mut offset = 2;
    while offset < bytes.len() {
        if bytes.get(offset) != Some(&0xff) {
            return Err(MosaicMediaError::InvalidJpeg);
        }
        offset += 1;

        while bytes.get(offset) == Some(&0xff) {
            offset += 1;
        }

        let marker = match bytes.get(offset) {
            Some(value) => *value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        offset += 1;

        if marker == 0xda || marker == 0xd9 {
            return Ok(NORMAL_EXIF_ORIENTATION);
        }

        if marker == 0x01 || (0xd0..=0xd7).contains(&marker) {
            continue;
        }

        let length_end = match offset.checked_add(2) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let length_bytes = match bytes.get(offset..length_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let segment_len = usize::from(u16::from_be_bytes([length_bytes[0], length_bytes[1]]));
        if segment_len < 2 {
            return Err(MosaicMediaError::InvalidJpeg);
        }

        let segment_end = match offset.checked_add(segment_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let payload_start = offset + 2;
        let payload = match bytes.get(payload_start..segment_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };

        if marker == 0xe1 && payload.starts_with(b"Exif\0\0") {
            return Ok(parse_tiff_orientation(&payload[6..]));
        }

        offset = segment_end;
    }

    Ok(NORMAL_EXIF_ORIENTATION)
}

fn parse_tiff_orientation(tiff: &[u8]) -> u8 {
    let little_endian = match tiff.get(0..2) {
        Some(b"II") => true,
        Some(b"MM") => false,
        _ => return NORMAL_EXIF_ORIENTATION,
    };

    if read_tiff_u16(tiff, 2, little_endian) != Some(42) {
        return NORMAL_EXIF_ORIENTATION;
    }

    let ifd_offset =
        match read_tiff_u32(tiff, 4, little_endian).and_then(|value| usize::try_from(value).ok()) {
            Some(value) => value,
            None => return NORMAL_EXIF_ORIENTATION,
        };
    let entry_count = match read_tiff_u16(tiff, ifd_offset, little_endian) {
        Some(value) => value,
        None => return NORMAL_EXIF_ORIENTATION,
    };
    let entries_start = match ifd_offset.checked_add(2) {
        Some(value) => value,
        None => return NORMAL_EXIF_ORIENTATION,
    };

    for entry_index in 0..entry_count {
        let entry_offset = match entries_start.checked_add(usize::from(entry_index) * 12) {
            Some(value) => value,
            None => return NORMAL_EXIF_ORIENTATION,
        };
        let entry_end = match entry_offset.checked_add(12) {
            Some(value) => value,
            None => return NORMAL_EXIF_ORIENTATION,
        };
        if tiff.get(entry_offset..entry_end).is_none() {
            return NORMAL_EXIF_ORIENTATION;
        }

        let tag = read_tiff_u16(tiff, entry_offset, little_endian);
        if tag != Some(0x0112) {
            continue;
        }

        let value_type = read_tiff_u16(tiff, entry_offset + 2, little_endian);
        let value_count = read_tiff_u32(tiff, entry_offset + 4, little_endian);
        if value_type != Some(3) || value_count != Some(1) {
            return NORMAL_EXIF_ORIENTATION;
        }

        let orientation = read_tiff_u16(tiff, entry_offset + 8, little_endian)
            .unwrap_or(u16::from(NORMAL_EXIF_ORIENTATION));
        return canonical_exif_orientation(orientation);
    }

    NORMAL_EXIF_ORIENTATION
}

fn read_tiff_u16(bytes: &[u8], offset: usize, little_endian: bool) -> Option<u16> {
    let end = offset.checked_add(2)?;
    let data = bytes.get(offset..end)?;
    let raw = [data[0], data[1]];
    Some(if little_endian {
        u16::from_le_bytes(raw)
    } else {
        u16::from_be_bytes(raw)
    })
}

fn read_tiff_u32(bytes: &[u8], offset: usize, little_endian: bool) -> Option<u32> {
    let end = offset.checked_add(4)?;
    let data = bytes.get(offset..end)?;
    let raw = [data[0], data[1], data[2], data[3]];
    Some(if little_endian {
        u32::from_le_bytes(raw)
    } else {
        u32::from_be_bytes(raw)
    })
}

fn canonical_exif_orientation(orientation: u16) -> u8 {
    if (1..=8).contains(&orientation) {
        orientation as u8
    } else {
        NORMAL_EXIF_ORIENTATION
    }
}

fn orientation_swaps_dimensions(orientation: u8) -> bool {
    matches!(orientation, 5..=8)
}

fn inspect_jpeg_dimensions(bytes: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if !bytes.starts_with(&[0xff, 0xd8]) {
        return Err(MosaicMediaError::InvalidJpeg);
    }

    let mut offset = 2;
    while offset < bytes.len() {
        if bytes.get(offset) != Some(&0xff) {
            return Err(MosaicMediaError::InvalidJpeg);
        }
        offset += 1;

        while bytes.get(offset) == Some(&0xff) {
            offset += 1;
        }

        let marker = match bytes.get(offset) {
            Some(value) => *value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        offset += 1;

        if marker == 0xda || marker == 0xd9 {
            return Err(MosaicMediaError::InvalidJpeg);
        }

        if marker == 0x01 || (0xd0..=0xd7).contains(&marker) {
            continue;
        }

        let length_end = match offset.checked_add(2) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let length_bytes = match bytes.get(offset..length_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let segment_len = usize::from(u16::from_be_bytes([length_bytes[0], length_bytes[1]]));
        if segment_len < 2 {
            return Err(MosaicMediaError::InvalidJpeg);
        }

        let segment_end = match offset.checked_add(segment_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let payload_start = offset + 2;
        let payload = match bytes.get(payload_start..segment_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };

        if is_jpeg_start_of_frame(marker) {
            if payload.len() < 5 {
                return Err(MosaicMediaError::InvalidJpeg);
            }
            let height = u32::from(u16::from_be_bytes([payload[1], payload[2]]));
            let width = u32::from(u16::from_be_bytes([payload[3], payload[4]]));
            // DNL-deferred JPEG height uses zero in SOF and requires scanning past
            // the first entropy-coded scan; this header-only gate rejects it.
            return validate_dimensions(width, height);
        }

        offset = segment_end;
    }

    Err(MosaicMediaError::InvalidJpeg)
}

fn is_jpeg_start_of_frame(marker: u8) -> bool {
    matches!(
        marker,
        0xc0 | 0xc1 | 0xc2 | 0xc3 | 0xc5 | 0xc6 | 0xc7 | 0xc9 | 0xca | 0xcb | 0xcd | 0xce | 0xcf
    )
}

fn inspect_png_dimensions(bytes: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if !bytes.starts_with(PNG_SIGNATURE) {
        return Err(MosaicMediaError::InvalidPng);
    }

    let mut offset = PNG_SIGNATURE.len();
    let length_bytes = match bytes.get(offset..offset + 4) {
        Some(value) => value,
        None => return Err(MosaicMediaError::InvalidPng),
    };
    let payload_len = u32::from_be_bytes([
        length_bytes[0],
        length_bytes[1],
        length_bytes[2],
        length_bytes[3],
    ]);
    if payload_len != 13 {
        return Err(MosaicMediaError::InvalidPng);
    }
    offset += 4;

    if bytes.get(offset..offset + 4) != Some(b"IHDR") {
        return Err(MosaicMediaError::InvalidPng);
    }
    offset += 4;

    let payload = match bytes.get(offset..offset + 13) {
        Some(value) => value,
        None => return Err(MosaicMediaError::InvalidPng),
    };
    let width = u32::from_be_bytes([payload[0], payload[1], payload[2], payload[3]]);
    let height = u32::from_be_bytes([payload[4], payload[5], payload[6], payload[7]]);
    validate_dimensions(width, height)
}

fn inspect_webp_dimensions(bytes: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if bytes.len() < 12 || !bytes.starts_with(b"RIFF") || bytes.get(8..12) != Some(b"WEBP") {
        return Err(MosaicMediaError::InvalidWebP);
    }

    let mut offset = 12;
    while offset < bytes.len() {
        let kind_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let chunk_type = match bytes.get(offset..kind_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        offset = kind_end;

        let size_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let size_bytes = match bytes.get(offset..size_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let payload_len_u32 =
            u32::from_le_bytes([size_bytes[0], size_bytes[1], size_bytes[2], size_bytes[3]]);
        let payload_len = match usize::try_from(payload_len_u32) {
            Ok(value) => value,
            Err(_) => return Err(MosaicMediaError::InvalidWebP),
        };
        offset = size_end;

        let payload_end = match offset.checked_add(payload_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let padded_end = match payload_end.checked_add(payload_len % 2) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let payload = match bytes.get(offset..payload_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        if bytes.get(payload_end..padded_end).is_none() {
            return Err(MosaicMediaError::InvalidWebP);
        }

        if let Some(dimensions) = inspect_webp_dimension_chunk(chunk_type, payload)? {
            return Ok(dimensions);
        }

        offset = padded_end;
    }

    Err(MosaicMediaError::InvalidWebP)
}

fn inspect_webp_dimension_chunk(
    chunk_type: &[u8],
    payload: &[u8],
) -> Result<Option<(u32, u32)>, MosaicMediaError> {
    match chunk_type {
        b"VP8 " => inspect_vp8_dimensions(payload).map(Some),
        b"VP8L" => inspect_vp8l_dimensions(payload).map(Some),
        b"VP8X" => inspect_vp8x_dimensions(payload).map(Some),
        _ => Ok(None),
    }
}

fn inspect_vp8_dimensions(payload: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if payload.len() < 10 || payload.get(3..6) != Some(&[0x9d, 0x01, 0x2a]) {
        return Err(MosaicMediaError::InvalidWebP);
    }

    let width = u32::from(u16::from_le_bytes([payload[6], payload[7]]) & 0x3fff);
    let height = u32::from(u16::from_le_bytes([payload[8], payload[9]]) & 0x3fff);
    validate_dimensions(width, height)
}

fn inspect_vp8l_dimensions(payload: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if payload.len() < 5 || payload[0] != 0x2f {
        return Err(MosaicMediaError::InvalidWebP);
    }

    let bits = u32::from_le_bytes([payload[1], payload[2], payload[3], payload[4]]);
    let width = (bits & 0x3fff) + 1;
    let height = ((bits >> 14) & 0x3fff) + 1;
    validate_dimensions(width, height)
}

fn inspect_vp8x_dimensions(payload: &[u8]) -> Result<(u32, u32), MosaicMediaError> {
    if payload.len() < 10 {
        return Err(MosaicMediaError::InvalidWebP);
    }

    let width = read_u24_le(&payload[4..7]) + 1;
    let height = read_u24_le(&payload[7..10]) + 1;
    validate_dimensions(width, height)
}

fn read_u24_le(bytes: &[u8]) -> u32 {
    u32::from(bytes[0]) | (u32::from(bytes[1]) << 8) | (u32::from(bytes[2]) << 16)
}

fn strip_jpeg_metadata(bytes: &[u8]) -> Result<StrippedMedia, MosaicMediaError> {
    if !bytes.starts_with(&[0xff, 0xd8]) {
        return Err(MosaicMediaError::InvalidJpeg);
    }

    let mut output = Vec::with_capacity(bytes.len());
    let mut removed = Vec::new();
    output.extend_from_slice(&bytes[..2]);

    let mut offset = 2;
    while offset < bytes.len() {
        let marker_start = offset;
        if bytes.get(offset) != Some(&0xff) {
            return Err(MosaicMediaError::InvalidJpeg);
        }
        offset += 1;

        while bytes.get(offset) == Some(&0xff) {
            offset += 1;
        }

        let marker = match bytes.get(offset) {
            Some(value) => *value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        offset += 1;

        if marker == 0xda {
            output.extend_from_slice(&bytes[marker_start..]);
            return Ok(StrippedMedia {
                bytes: output,
                removed,
            });
        }

        if marker == 0xd9 || marker == 0x01 || (0xd0..=0xd7).contains(&marker) {
            output.extend_from_slice(&bytes[marker_start..offset]);
            continue;
        }

        let length_end = match offset.checked_add(2) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let length_bytes = match bytes.get(offset..length_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let segment_len = usize::from(u16::from_be_bytes([length_bytes[0], length_bytes[1]]));
        if segment_len < 2 {
            return Err(MosaicMediaError::InvalidJpeg);
        }

        let segment_end = match offset.checked_add(segment_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };
        let payload_start = offset + 2;
        let payload = match bytes.get(payload_start..segment_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidJpeg),
        };

        if let Some(kind) = classify_jpeg_metadata(marker, payload) {
            removed.push(kind);
        } else {
            output.extend_from_slice(&bytes[marker_start..segment_end]);
        }
        offset = segment_end;
    }

    Ok(StrippedMedia {
        bytes: output,
        removed,
    })
}

fn classify_jpeg_metadata(marker: u8, payload: &[u8]) -> Option<MetadataKind> {
    match marker {
        0xe1 if payload.starts_with(b"Exif\0\0") => Some(MetadataKind::Exif),
        0xe1 if payload.starts_with(b"http://ns.adobe.com/xap/1.0/") => Some(MetadataKind::Xmp),
        0xe1 if payload.starts_with(b"http://ns.adobe.com/xmp/extension/\0") => {
            Some(MetadataKind::Xmp)
        }
        0xe2 if payload.starts_with(b"ICC_PROFILE\0") => Some(MetadataKind::ColorProfile),
        0xed => Some(MetadataKind::Iptc),
        0xfe => Some(MetadataKind::Comment),
        // APPn segments are application-defined and routinely carry device,
        // editor, thumbnail, caption, or color metadata outside EXIF/XMP/IPTC.
        0xe0..=0xef => Some(MetadataKind::RenderingHint),
        _ => None,
    }
}

fn strip_png_metadata(bytes: &[u8]) -> Result<StrippedMedia, MosaicMediaError> {
    if !bytes.starts_with(PNG_SIGNATURE) {
        return Err(MosaicMediaError::InvalidPng);
    }

    let mut output = Vec::with_capacity(bytes.len());
    let mut removed = Vec::new();
    output.extend_from_slice(PNG_SIGNATURE);

    let mut offset = PNG_SIGNATURE.len();
    while offset < bytes.len() {
        let chunk_start = offset;
        let length_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        let length_bytes = match bytes.get(offset..length_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        let payload_len_u32 = u32::from_be_bytes([
            length_bytes[0],
            length_bytes[1],
            length_bytes[2],
            length_bytes[3],
        ]);
        let payload_len = match usize::try_from(payload_len_u32) {
            Ok(value) => value,
            Err(_) => return Err(MosaicMediaError::InvalidPng),
        };
        offset = length_end;

        let chunk_type_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        let chunk_type = match bytes.get(offset..chunk_type_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        offset = chunk_type_end;

        let payload_end = match offset.checked_add(payload_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        let crc_end = match payload_end.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidPng),
        };
        if bytes.get(offset..payload_end).is_none() || bytes.get(payload_end..crc_end).is_none() {
            return Err(MosaicMediaError::InvalidPng);
        }

        if let Some(kind) = classify_png_metadata(chunk_type) {
            removed.push(kind);
        } else {
            output.extend_from_slice(&bytes[chunk_start..crc_end]);
        }
        offset = crc_end;
    }

    Ok(StrippedMedia {
        bytes: output,
        removed,
    })
}

fn classify_png_metadata(chunk_type: &[u8]) -> Option<MetadataKind> {
    match chunk_type {
        b"eXIf" => Some(MetadataKind::Exif),
        b"iTXt" | b"tEXt" | b"zTXt" => Some(MetadataKind::Text),
        b"tIME" => Some(MetadataKind::Timestamp),
        b"iCCP" | b"sRGB" | b"cHRM" | b"gAMA" => Some(MetadataKind::ColorProfile),
        b"pHYs" => Some(MetadataKind::PhysicalDimensions),
        b"sPLT" => Some(MetadataKind::SuggestedPalette),
        b"bKGD" | b"hIST" => Some(MetadataKind::RenderingHint),
        _ => None,
    }
}

fn strip_webp_metadata(bytes: &[u8]) -> Result<StrippedMedia, MosaicMediaError> {
    if bytes.len() < 12 || !bytes.starts_with(b"RIFF") || bytes.get(8..12) != Some(b"WEBP") {
        return Err(MosaicMediaError::InvalidWebP);
    }

    let mut output = b"RIFF\0\0\0\0WEBP".to_vec();
    let mut removed = Vec::new();
    let mut offset = 12;

    while offset < bytes.len() {
        let chunk_start = offset;
        let kind_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let chunk_type = match bytes.get(offset..kind_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        offset = kind_end;

        let size_end = match offset.checked_add(4) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let size_bytes = match bytes.get(offset..size_end) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let payload_len_u32 =
            u32::from_le_bytes([size_bytes[0], size_bytes[1], size_bytes[2], size_bytes[3]]);
        let payload_len = match usize::try_from(payload_len_u32) {
            Ok(value) => value,
            Err(_) => return Err(MosaicMediaError::InvalidWebP),
        };
        offset = size_end;

        let payload_end = match offset.checked_add(payload_len) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        let padded_end = match payload_end.checked_add(payload_len % 2) {
            Some(value) => value,
            None => return Err(MosaicMediaError::InvalidWebP),
        };
        if bytes.get(offset..payload_end).is_none() || bytes.get(payload_end..padded_end).is_none()
        {
            return Err(MosaicMediaError::InvalidWebP);
        }

        if let Some(kind) = classify_webp_metadata(chunk_type) {
            removed.push(kind);
        } else {
            output.extend_from_slice(&bytes[chunk_start..padded_end]);
        }
        offset = padded_end;
    }

    let riff_size = match u32::try_from(output.len() - 8) {
        Ok(value) => value,
        Err(_) => return Err(MosaicMediaError::OutputTooLarge),
    };
    output[4..8].copy_from_slice(&riff_size.to_le_bytes());

    Ok(StrippedMedia {
        bytes: output,
        removed,
    })
}

fn classify_webp_metadata(chunk_type: &[u8]) -> Option<MetadataKind> {
    match chunk_type {
        b"EXIF" => Some(MetadataKind::Exif),
        b"XMP " => Some(MetadataKind::Xmp),
        b"ICCP" => Some(MetadataKind::ColorProfile),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;

    use super::{
        GeneratedTiers, ImageMetadata, MediaFormat, MediaTierEncoder, MetadataKind,
        MosaicMediaError, TierOutput, extract_exif_orientation, generate_tiers,
        generate_tiers_with_metadata, inspect_image, normalize_dimensions_by_orientation,
    };
    use super::{
        MAX_IMAGE_PIXELS, NORMAL_EXIF_ORIENTATION, PREVIEW_MAX_DIMENSION, THUMBNAIL_MAX_DIMENSION,
        TierDimensions, plan_tier_layout, strip_known_metadata,
    };
    use mosaic_domain::ShardTier;

    #[test]
    fn uses_domain_protocol_version() {
        assert_eq!(super::protocol_version(), "mosaic-v1");
    }

    #[test]
    fn plans_landscape_tier_layout() {
        let layout = expect_tier_layout(4032, 3024);

        assert_eq!(
            layout.tiers(),
            [
                tier(ShardTier::Thumbnail, 256, 192),
                tier(ShardTier::Preview, 1024, 768),
                tier(ShardTier::Original, 4032, 3024),
            ]
        );
        assert_eq!(layout.original.width, 4032);
        assert_eq!(layout.original.height, 3024);
    }

    #[test]
    fn plans_portrait_tier_layout() {
        let layout = expect_tier_layout(3024, 4032);

        assert_eq!(
            layout.tiers(),
            [
                tier(ShardTier::Thumbnail, 192, 256),
                tier(ShardTier::Preview, 768, 1024),
                tier(ShardTier::Original, 3024, 4032),
            ]
        );
    }

    #[test]
    fn plans_square_tier_layout() {
        let layout = expect_tier_layout(3000, 3000);

        assert_eq!(
            layout.tiers(),
            [
                tier(ShardTier::Thumbnail, 256, 256),
                tier(ShardTier::Preview, 1024, 1024),
                tier(ShardTier::Original, 3000, 3000),
            ]
        );
    }

    #[test]
    fn does_not_upscale_small_sources() {
        let layout = expect_tier_layout(128, 96);

        assert_eq!(
            layout.tiers(),
            [
                tier(ShardTier::Thumbnail, 128, 96),
                tier(ShardTier::Preview, 128, 96),
                tier(ShardTier::Original, 128, 96),
            ]
        );
    }

    #[test]
    fn uses_deterministic_integer_floor_scaling_for_non_divisible_aspect_ratios() {
        let layout = expect_tier_layout(3333, 2000);

        assert_eq!(layout.thumbnail, tier(ShardTier::Thumbnail, 256, 153));
        assert_eq!(layout.preview, tier(ShardTier::Preview, 1024, 614));
        assert!(
            u64::from(layout.thumbnail.height) * 3333 <= 2000 * u64::from(layout.thumbnail.width)
        );
        assert!(
            u64::from(layout.thumbnail.height + 1) * 3333
                > 2000 * u64::from(layout.thumbnail.width)
        );
        assert!(u64::from(layout.preview.height) * 3333 <= 2000 * u64::from(layout.preview.width));
        assert!(
            u64::from(layout.preview.height + 1) * 3333 > 2000 * u64::from(layout.preview.width)
        );
    }

    #[test]
    fn extreme_aspect_ratio_clamps_secondary_dimension_to_one() {
        let wide = expect_tier_layout(MAX_IMAGE_PIXELS, 1);
        assert_eq!(wide.thumbnail, tier(ShardTier::Thumbnail, 256, 1));
        assert_eq!(wide.preview, tier(ShardTier::Preview, 1024, 1));
        assert_eq!(
            wide.original,
            tier(ShardTier::Original, MAX_IMAGE_PIXELS, 1)
        );

        let tall = expect_tier_layout(1, MAX_IMAGE_PIXELS);
        assert_eq!(tall.thumbnail, tier(ShardTier::Thumbnail, 1, 256));
        assert_eq!(tall.preview, tier(ShardTier::Preview, 1, 1024));
        assert_eq!(
            tall.original,
            tier(ShardTier::Original, 1, MAX_IMAGE_PIXELS)
        );
    }

    #[test]
    fn rejects_zero_and_excessive_dimensions_for_tier_layout() {
        assert_eq!(
            plan_tier_layout(0, 1),
            Err(MosaicMediaError::InvalidDimensions)
        );
        assert_eq!(
            plan_tier_layout(1, 0),
            Err(MosaicMediaError::InvalidDimensions)
        );
        assert_eq!(
            plan_tier_layout(MAX_IMAGE_PIXELS + 1, 1),
            Err(MosaicMediaError::InvalidDimensions)
        );
    }

    #[test]
    fn plans_from_orientation_normalized_inspection_dimensions() {
        let input = jpeg_with_segments(&[
            jpeg_exif_orientation_segment(6, false),
            jpeg_sof_segment(0xc0, 3024, 4032),
        ]);
        let metadata = match inspect_image(&input) {
            Ok(value) => value,
            Err(error) => panic!("orientation-swapped JPEG should inspect: {error:?}"),
        };

        assert_eq!(
            (metadata.width, metadata.height, metadata.orientation),
            (3024, 4032, 6)
        );

        let layout = expect_tier_layout(metadata.width, metadata.height);
        assert_eq!(
            layout.tiers(),
            [
                tier(ShardTier::Thumbnail, 192, 256),
                tier(ShardTier::Preview, 768, 1024),
                tier(ShardTier::Original, 3024, 4032),
            ]
        );
    }

    #[test]
    fn generates_tiers_from_sanitized_orientation_normalized_jpeg() {
        let input = jpeg_with_segments(&[
            jpeg_exif_orientation_segment(6, false),
            jpeg_segment(0xec, b"caption=private"),
            jpeg_sof_segment(0xc0, 3024, 4032),
        ]);
        let encoder = FakeEncoder::default();

        let generated = expect_generated_tiers(&input, &encoder);

        assert_eq!(
            encoder.requested_dimensions(),
            vec![
                tier(ShardTier::Thumbnail, 192, 256),
                tier(ShardTier::Preview, 768, 1024),
            ]
        );
        assert_eq!(
            encoder.requested_metadata(),
            vec![
                ImageMetadata {
                    format: MediaFormat::Jpeg,
                    mime_type: "image/jpeg",
                    width: 3024,
                    height: 4032,
                    orientation: 6,
                },
                ImageMetadata {
                    format: MediaFormat::Jpeg,
                    mime_type: "image/jpeg",
                    width: 3024,
                    height: 4032,
                    orientation: 6,
                },
            ]
        );
        assert!(
            encoder
                .requested_sources()
                .iter()
                .all(|source| !contains_ascii(source, b"Exif"))
        );
        assert!(
            encoder
                .requested_sources()
                .iter()
                .all(|source| !contains_ascii(source, b"caption=private"))
        );

        assert_eq!(
            generated.tiers(),
            &[
                output(
                    ShardTier::Thumbnail,
                    192,
                    256,
                    encoded_bytes(ShardTier::Thumbnail, 192, 256),
                ),
                output(
                    ShardTier::Preview,
                    768,
                    1024,
                    encoded_bytes(ShardTier::Preview, 768, 1024),
                ),
                output(
                    ShardTier::Original,
                    3024,
                    4032,
                    match strip_known_metadata(MediaFormat::Jpeg, &input) {
                        Ok(value) => value.bytes,
                        Err(error) => panic!("test JPEG should strip: {error:?}"),
                    },
                ),
            ]
        );
        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &generated.tiers()[2].bytes),
            Ok(1)
        );
        assert!(!contains_ascii(&generated.tiers()[2].bytes, b"Exif"));
        assert!(!contains_ascii(
            &generated.tiers()[2].bytes,
            b"caption=private"
        ));
    }

    #[test]
    fn generates_tiers_with_already_inspected_metadata() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(640, 480),
            png_chunk(*b"tEXt", b"caption=private"),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let metadata = match inspect_image(&input) {
            Ok(value) => value,
            Err(error) => panic!("test PNG should inspect: {error:?}"),
        };
        let encoder = FakeEncoder::default();

        let generated = match generate_tiers_with_metadata(&input, metadata, &encoder) {
            Ok(value) => value,
            Err(error) => panic!("tiers should generate from inspected metadata: {error:?}"),
        };

        assert_eq!(
            encoder.requested_dimensions(),
            vec![
                tier(ShardTier::Thumbnail, 256, 192),
                tier(ShardTier::Preview, 640, 480),
            ]
        );
        assert_eq!(generated.tiers()[2].tier, ShardTier::Original);
        assert_eq!(
            (generated.tiers()[2].width, generated.tiers()[2].height),
            (640, 480)
        );
        assert!(!contains_ascii(
            &generated.tiers()[2].bytes,
            b"caption=private"
        ));
    }

    #[test]
    fn rejects_mismatched_already_inspected_metadata_before_adapter_call() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(640, 480),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::default();
        let stale_metadata = ImageMetadata {
            format: MediaFormat::Png,
            mime_type: "image/png",
            width: 320,
            height: 240,
            orientation: NORMAL_EXIF_ORIENTATION,
        };

        assert_eq!(
            generate_tiers_with_metadata(&input, stale_metadata, &encoder),
            Err(MosaicMediaError::ImageMetadataMismatch)
        );
        assert!(encoder.requests().is_empty());
    }

    #[test]
    fn generated_tiers_are_returned_in_canonical_order() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(3000, 3000),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::default();

        let generated = expect_generated_tiers(&input, &encoder);

        let tiers = generated.tiers();
        assert_eq!(
            tiers.each_ref().map(|output| output.tier),
            [
                ShardTier::Thumbnail,
                ShardTier::Preview,
                ShardTier::Original,
            ]
        );
        assert_eq!(
            tiers.each_ref().map(|output| (output.width, output.height)),
            [(256, 256), (1024, 1024), (3000, 3000)]
        );
    }

    #[test]
    fn rejects_adapter_output_tier_or_dimension_mismatches() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(640, 480),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::with_output_override(tier(ShardTier::Preview, 255, 192));

        assert_eq!(
            generate_tiers(&input, &encoder),
            Err(MosaicMediaError::EncodedTierMismatch {
                expected: tier(ShardTier::Thumbnail, 256, 192),
                actual: tier(ShardTier::Preview, 255, 192),
            })
        );
        assert_eq!(
            encoder.requested_dimensions(),
            vec![tier(ShardTier::Thumbnail, 256, 192)]
        );
    }

    #[test]
    fn propagates_adapter_errors_without_swallowing() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(640, 480),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::with_error(MosaicMediaError::OutputTooLarge);

        assert_eq!(
            generate_tiers(&input, &encoder),
            Err(MosaicMediaError::OutputTooLarge)
        );
        assert_eq!(
            encoder.requested_dimensions(),
            vec![tier(ShardTier::Thumbnail, 256, 192)]
        );
    }

    #[test]
    fn rejects_unsupported_or_malformed_input_before_adapter_call() {
        let unsupported_encoder = FakeEncoder::default();
        assert_eq!(
            generate_tiers(b"not an image", &unsupported_encoder),
            Err(MosaicMediaError::UnsupportedFormat)
        );
        assert!(unsupported_encoder.requests().is_empty());

        let malformed_encoder = FakeEncoder::default();
        assert_eq!(
            generate_tiers(&[0xff, 0xd8], &malformed_encoder),
            Err(MosaicMediaError::InvalidJpeg)
        );
        assert!(malformed_encoder.requests().is_empty());
    }

    #[test]
    fn generation_does_not_upscale_small_sources() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(128, 96),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::default();

        let generated = expect_generated_tiers(&input, &encoder);

        assert_eq!(
            encoder.requested_dimensions(),
            vec![
                tier(ShardTier::Thumbnail, 128, 96),
                tier(ShardTier::Preview, 128, 96),
            ]
        );
        assert_eq!(
            generated
                .tiers()
                .each_ref()
                .map(|output| (output.width, output.height)),
            [(128, 96), (128, 96), (128, 96)]
        );
    }

    #[test]
    fn generation_preserves_non_zero_dimensions_for_extreme_valid_aspect_ratio() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(MAX_IMAGE_PIXELS, 1),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);
        let encoder = FakeEncoder::default();

        let generated = expect_generated_tiers(&input, &encoder);

        assert_eq!(
            encoder.requested_dimensions(),
            vec![
                tier(ShardTier::Thumbnail, 256, 1),
                tier(ShardTier::Preview, 1024, 1),
            ]
        );
        assert_eq!(
            generated
                .tiers()
                .each_ref()
                .map(|output| (output.width, output.height)),
            [(256, 1), (1024, 1), (MAX_IMAGE_PIXELS, 1)]
        );
    }

    #[test]
    fn strips_jpeg_exif_xmp_iptc_and_comment_segments_before_scan() {
        let input = jpeg_with_segments(&[
            jpeg_segment(0xe1, b"Exif\0\0gps coordinates"),
            jpeg_segment(0xe1, b"http://ns.adobe.com/xap/1.0/\0xmp payload"),
            jpeg_segment(
                0xe1,
                b"http://ns.adobe.com/xmp/extension/\0extended xmp payload",
            ),
            jpeg_segment(0xed, b"Photoshop 3.0\0iptc caption"),
            jpeg_segment(0xfe, b"plain comment"),
            jpeg_segment(0xdb, &[0_u8; 65]),
        ]);

        let stripped = match strip_known_metadata(MediaFormat::Jpeg, &input) {
            Ok(value) => value,
            Err(error) => panic!("JPEG metadata should strip: {error:?}"),
        };

        assert_eq!(
            stripped.removed,
            vec![
                MetadataKind::Exif,
                MetadataKind::Xmp,
                MetadataKind::Xmp,
                MetadataKind::Iptc,
                MetadataKind::Comment,
            ]
        );
        assert!(!contains_ascii(&stripped.bytes, b"Exif"));
        assert!(!contains_ascii(&stripped.bytes, b"xmp payload"));
        assert!(!contains_ascii(&stripped.bytes, b"extended xmp payload"));
        assert!(!contains_ascii(&stripped.bytes, b"iptc caption"));
        assert!(!contains_ascii(&stripped.bytes, b"plain comment"));
        assert!(contains_ascii(&stripped.bytes, b"scan bytes"));
    }

    #[test]
    fn strips_jpeg_application_segments_that_can_carry_private_metadata() {
        let input = jpeg_with_segments(&[
            jpeg_segment(0xe0, b"JFIF\0\x01\x02embedded thumbnail"),
            jpeg_segment(0xe3, b"camera serial number"),
            jpeg_segment(0xec, b"caption=private"),
            jpeg_segment(0xee, b"Adobe encoder details"),
            jpeg_sof_segment(0xc0, 480, 640),
        ]);

        let stripped = match strip_known_metadata(MediaFormat::Jpeg, &input) {
            Ok(value) => value,
            Err(error) => panic!("JPEG APP metadata should strip: {error:?}"),
        };

        assert_eq!(
            stripped.removed,
            vec![
                MetadataKind::RenderingHint,
                MetadataKind::RenderingHint,
                MetadataKind::RenderingHint,
                MetadataKind::RenderingHint,
            ]
        );
        assert!(!contains_ascii(&stripped.bytes, b"embedded thumbnail"));
        assert!(!contains_ascii(&stripped.bytes, b"camera serial number"));
        assert!(!contains_ascii(&stripped.bytes, b"caption=private"));
        assert!(!contains_ascii(&stripped.bytes, b"Adobe encoder details"));
        assert!(contains_ascii(&stripped.bytes, b"scan bytes"));
    }

    #[test]
    fn strips_png_text_exif_time_and_color_profile_chunks() {
        let input = png_with_chunks(&[
            png_chunk(*b"IHDR", b"\0\0\0\x01\0\0\0\x01\x08\x02\0\0\0"),
            png_chunk(*b"eXIf", b"gps coordinates"),
            png_chunk(*b"iTXt", b"caption\0\0\0\0\0Hello"),
            png_chunk(*b"tIME", &[1, 2, 3, 4, 5, 6, 7]),
            png_chunk(*b"iCCP", b"profile\0\0payload"),
            png_chunk(*b"pHYs", &[0, 0, 0x0b, 0x13, 0, 0, 0x0b, 0x13, 1]),
            png_chunk(*b"sPLT", b"editing palette\0\x08"),
            png_chunk(*b"bKGD", &[0, 1, 0, 2, 0, 3]),
            png_chunk(*b"hIST", &[0, 1, 0, 2]),
            png_chunk(*b"tRNS", b"rendering transparency"),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);

        let stripped = match strip_known_metadata(MediaFormat::Png, &input) {
            Ok(value) => value,
            Err(error) => panic!("PNG metadata should strip: {error:?}"),
        };

        assert_eq!(
            stripped.removed,
            vec![
                MetadataKind::Exif,
                MetadataKind::Text,
                MetadataKind::Timestamp,
                MetadataKind::ColorProfile,
                MetadataKind::PhysicalDimensions,
                MetadataKind::SuggestedPalette,
                MetadataKind::RenderingHint,
                MetadataKind::RenderingHint,
            ]
        );
        assert!(!contains_ascii(&stripped.bytes, b"eXIf"));
        assert!(!contains_ascii(&stripped.bytes, b"caption"));
        assert!(!contains_ascii(&stripped.bytes, b"iCCP"));
        assert!(!contains_ascii(&stripped.bytes, b"pHYs"));
        assert!(!contains_ascii(&stripped.bytes, b"editing palette"));
        assert!(!contains_ascii(&stripped.bytes, b"bKGD"));
        assert!(!contains_ascii(&stripped.bytes, b"hIST"));
        assert!(contains_ascii(&stripped.bytes, b"tRNS"));
        assert!(contains_ascii(&stripped.bytes, b"rendering transparency"));
        assert!(contains_ascii(&stripped.bytes, b"IDAT"));
        assert!(contains_ascii(&stripped.bytes, b"pixel bytes"));
    }

    #[test]
    fn strips_webp_exif_xmp_and_color_profile_chunks_and_updates_riff_size() {
        let input = webp_with_chunks(&[
            webp_chunk(*b"VP8 ", b"image bytes"),
            webp_chunk(*b"EXIF", b"gps coordinates"),
            webp_chunk(*b"XMP ", b"xmp caption"),
            webp_chunk(*b"ICCP", b"profile"),
        ]);

        let stripped = match strip_known_metadata(MediaFormat::WebP, &input) {
            Ok(value) => value,
            Err(error) => panic!("WebP metadata should strip: {error:?}"),
        };

        assert_eq!(
            stripped.removed,
            vec![
                MetadataKind::Exif,
                MetadataKind::Xmp,
                MetadataKind::ColorProfile,
            ]
        );
        assert!(!contains_ascii(&stripped.bytes, b"EXIF"));
        assert!(!contains_ascii(&stripped.bytes, b"xmp caption"));
        assert!(!contains_ascii(&stripped.bytes, b"ICCP"));
        assert!(contains_ascii(&stripped.bytes, b"VP8 "));
        assert!(contains_ascii(&stripped.bytes, b"image bytes"));

        let declared_size = u32::from_le_bytes([
            stripped.bytes[4],
            stripped.bytes[5],
            stripped.bytes[6],
            stripped.bytes[7],
        ]);
        assert_eq!(usize::try_from(declared_size), Ok(stripped.bytes.len() - 8));
    }

    #[test]
    fn inspects_jpeg_dimensions_from_start_of_frame() {
        let input = jpeg_with_segments(&[
            jpeg_segment(0xe1, b"Exif\0\0gps coordinates"),
            jpeg_sof_segment(0xc0, 3024, 4032),
            jpeg_segment(0xdb, &[0_u8; 65]),
        ]);

        assert_eq!(
            inspect_image(&input),
            Ok(ImageMetadata {
                format: MediaFormat::Jpeg,
                mime_type: "image/jpeg",
                width: 4032,
                height: 3024,
                orientation: 1,
            })
        );
    }

    #[test]
    fn inspects_jpeg_orientation_and_normalized_display_dimensions() {
        let input = jpeg_with_segments(&[
            jpeg_exif_orientation_segment(6, false),
            jpeg_sof_segment(0xc0, 3024, 4032),
        ]);

        assert_eq!(extract_exif_orientation(MediaFormat::Jpeg, &input), Ok(6));
        assert_eq!(
            inspect_image(&input),
            Ok(ImageMetadata {
                format: MediaFormat::Jpeg,
                mime_type: "image/jpeg",
                width: 3024,
                height: 4032,
                orientation: 6,
            })
        );
    }

    #[test]
    fn extracts_big_and_little_endian_jpeg_exif_orientation() {
        for little_endian in [false, true] {
            let input = jpeg_with_segments(&[
                jpeg_exif_orientation_segment(8, little_endian),
                jpeg_sof_segment(0xc0, 1200, 800),
            ]);

            assert_eq!(extract_exif_orientation(MediaFormat::Jpeg, &input), Ok(8));
        }
    }

    #[test]
    fn orientation_defaults_to_normal_when_absent_or_invalid() {
        let without_exif = jpeg_with_segments(&[jpeg_sof_segment(0xc0, 1200, 800)]);
        let invalid_orientation = jpeg_with_segments(&[
            jpeg_exif_orientation_segment(42, false),
            jpeg_sof_segment(0xc0, 1200, 800),
        ]);

        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &without_exif),
            Ok(1)
        );
        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &invalid_orientation),
            Ok(1)
        );
        assert_eq!(
            extract_exif_orientation(MediaFormat::Png, &png_with_chunks(&[png_ihdr_chunk(1, 1)])),
            Ok(1)
        );
    }

    #[test]
    fn malformed_tiff_orientation_metadata_defaults_to_normal() {
        let bad_byte_order = jpeg_with_segments(&[
            jpeg_exif_segment(b"ZZ\x00\x2a\x00\x00\x00\x08\x00\x00"),
            jpeg_sof_segment(0xc0, 1200, 800),
        ]);
        let bad_magic = jpeg_with_segments(&[
            jpeg_exif_segment(b"MM\x00\x00\x00\x00\x00\x08\x00\x00"),
            jpeg_sof_segment(0xc0, 1200, 800),
        ]);
        let truncated_ifd_entry = jpeg_with_segments(&[
            jpeg_exif_segment(b"MM\x00\x2a\x00\x00\x00\x08\x00\x01\x01\x12"),
            jpeg_sof_segment(0xc0, 1200, 800),
        ]);

        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &bad_byte_order),
            Ok(1)
        );
        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &bad_magic),
            Ok(1)
        );
        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &truncated_ifd_entry),
            Ok(1)
        );
    }

    #[test]
    fn normalizes_dimensions_only_for_rotated_or_transposed_orientations() {
        for orientation in [1, 2, 3, 4] {
            assert_eq!(
                normalize_dimensions_by_orientation(640, 480, orientation),
                Ok((640, 480))
            );
        }

        for orientation in [5, 6, 7, 8] {
            assert_eq!(
                normalize_dimensions_by_orientation(640, 480, orientation),
                Ok((480, 640))
            );
        }

        assert_eq!(
            normalize_dimensions_by_orientation(640, 480, 42),
            Ok((640, 480))
        );
    }

    #[test]
    fn stripped_jpeg_no_longer_exposes_orientation_metadata() {
        let input = jpeg_with_segments(&[
            jpeg_exif_orientation_segment(6, false),
            jpeg_sof_segment(0xc0, 3024, 4032),
        ]);

        let stripped = match strip_known_metadata(MediaFormat::Jpeg, &input) {
            Ok(value) => value,
            Err(error) => panic!("JPEG EXIF orientation should strip: {error:?}"),
        };

        assert_eq!(stripped.removed, vec![MetadataKind::Exif]);
        assert_eq!(
            extract_exif_orientation(MediaFormat::Jpeg, &stripped.bytes),
            Ok(1)
        );
        assert!(!contains_ascii(&stripped.bytes, b"Exif"));
    }

    #[test]
    fn inspects_png_dimensions_from_ihdr() {
        let input = png_with_chunks(&[
            png_ihdr_chunk(3840, 2160),
            png_chunk(*b"IDAT", b"pixel bytes"),
            png_chunk(*b"IEND", b""),
        ]);

        assert_eq!(
            inspect_image(&input),
            Ok(ImageMetadata {
                format: MediaFormat::Png,
                mime_type: "image/png",
                width: 3840,
                height: 2160,
                orientation: 1,
            })
        );
    }

    #[test]
    fn inspects_webp_dimensions_from_vp8_vp8l_and_vp8x_chunks() {
        let lossy = webp_with_chunks(&[webp_vp8_chunk(640, 480)]);
        let lossless = webp_with_chunks(&[webp_vp8l_chunk(1024, 768)]);
        let extended = webp_with_chunks(&[webp_vp8x_chunk(1920, 1080)]);

        assert_eq!(
            inspect_image(&lossy),
            Ok(ImageMetadata {
                format: MediaFormat::WebP,
                mime_type: "image/webp",
                width: 640,
                height: 480,
                orientation: 1,
            })
        );
        assert_eq!(
            inspect_image(&lossless),
            Ok(ImageMetadata {
                format: MediaFormat::WebP,
                mime_type: "image/webp",
                width: 1024,
                height: 768,
                orientation: 1,
            })
        );
        assert_eq!(
            inspect_image(&extended),
            Ok(ImageMetadata {
                format: MediaFormat::WebP,
                mime_type: "image/webp",
                width: 1920,
                height: 1080,
                orientation: 1,
            })
        );
    }

    #[test]
    fn inspection_rejects_truncated_or_unrecognized_headers() {
        assert_eq!(
            inspect_image(&[0xff, 0xd8]),
            Err(MosaicMediaError::InvalidJpeg)
        );
        assert_eq!(
            inspect_image(b"\x89PNG\r\n\x1a\n\0\0"),
            Err(MosaicMediaError::InvalidPng)
        );
        assert_eq!(
            inspect_image(b"RIFF\x04\0\0\0WEBP"),
            Err(MosaicMediaError::InvalidWebP)
        );
        assert_eq!(
            inspect_image(b"not an image"),
            Err(MosaicMediaError::UnsupportedFormat)
        );
    }

    #[test]
    fn inspection_rejects_zero_and_excessive_dimensions() {
        let zero_png = png_with_chunks(&[png_ihdr_chunk(0, 1)]);
        let excessive_png = png_with_chunks(&[png_ihdr_chunk(MAX_IMAGE_PIXELS + 1, 1)]);

        assert_eq!(
            inspect_image(&zero_png),
            Err(MosaicMediaError::InvalidDimensions)
        );
        assert_eq!(
            inspect_image(&excessive_png),
            Err(MosaicMediaError::InvalidDimensions)
        );
    }

    #[test]
    fn tier_layout_preserves_non_zero_secondary_dimension_for_valid_extreme_aspects() {
        let wide = expect_tier_layout(32_000, 1);
        assert_eq!(wide.thumbnail.width, THUMBNAIL_MAX_DIMENSION);
        assert_eq!(wide.thumbnail.height, 1);
        assert_eq!(wide.preview.width, PREVIEW_MAX_DIMENSION);
        assert_eq!(wide.preview.height, 1);

        let tall = expect_tier_layout(1, 32_000);
        assert_eq!(tall.thumbnail.width, 1);
        assert_eq!(tall.thumbnail.height, THUMBNAIL_MAX_DIMENSION);
        assert_eq!(tall.preview.width, 1);
        assert_eq!(tall.preview.height, PREVIEW_MAX_DIMENSION);
    }

    #[test]
    fn metadata_stripping_rejects_truncated_container_boundaries() {
        let mut truncated_jpeg = vec![0xff, 0xd8, 0xff, 0xe1];
        truncated_jpeg.extend_from_slice(&16_u16.to_be_bytes());
        truncated_jpeg.extend_from_slice(b"Exif");
        assert_eq!(
            strip_known_metadata(MediaFormat::Jpeg, &truncated_jpeg),
            Err(MosaicMediaError::InvalidJpeg)
        );

        let mut truncated_png = b"\x89PNG\r\n\x1a\n".to_vec();
        truncated_png.extend_from_slice(&4_u32.to_be_bytes());
        truncated_png.extend_from_slice(b"tEXt");
        truncated_png.push(b'x');
        assert_eq!(
            strip_known_metadata(MediaFormat::Png, &truncated_png),
            Err(MosaicMediaError::InvalidPng)
        );

        let malformed_webp = {
            let mut bytes = b"RIFF".to_vec();
            bytes.extend_from_slice(&16_u32.to_le_bytes());
            bytes.extend_from_slice(b"WEBP");
            bytes.extend_from_slice(b"EXIF");
            bytes.extend_from_slice(&8_u32.to_le_bytes());
            bytes.extend_from_slice(b"gps");
            bytes
        };
        assert_eq!(
            strip_known_metadata(MediaFormat::WebP, &malformed_webp),
            Err(MosaicMediaError::InvalidWebP)
        );
    }

    fn expect_tier_layout(width: u32, height: u32) -> super::TierLayout {
        match plan_tier_layout(width, height) {
            Ok(value) => value,
            Err(error) => panic!("tier layout should plan for {width}x{height}: {error:?}"),
        }
    }

    fn expect_generated_tiers(input: &[u8], encoder: &FakeEncoder) -> GeneratedTiers {
        match generate_tiers(input, encoder) {
            Ok(value) => value,
            Err(error) => panic!("tiers should generate: {error:?}"),
        }
    }

    fn tier(tier: ShardTier, width: u32, height: u32) -> TierDimensions {
        TierDimensions {
            tier,
            width,
            height,
        }
    }

    fn output(tier: ShardTier, width: u32, height: u32, bytes: Vec<u8>) -> TierOutput {
        TierOutput {
            tier,
            width,
            height,
            bytes,
        }
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    struct EncodeRequest {
        source: Vec<u8>,
        metadata: ImageMetadata,
        dimensions: TierDimensions,
    }

    #[derive(Debug, Default)]
    struct FakeEncoder {
        requests: RefCell<Vec<EncodeRequest>>,
        output_override: RefCell<Option<TierDimensions>>,
        error: RefCell<Option<MosaicMediaError>>,
    }

    impl FakeEncoder {
        fn with_output_override(output_dimensions: TierDimensions) -> Self {
            Self {
                output_override: RefCell::new(Some(output_dimensions)),
                ..Self::default()
            }
        }

        fn with_error(error: MosaicMediaError) -> Self {
            Self {
                error: RefCell::new(Some(error)),
                ..Self::default()
            }
        }

        fn requests(&self) -> Vec<EncodeRequest> {
            self.requests.borrow().clone()
        }

        fn requested_dimensions(&self) -> Vec<TierDimensions> {
            self.requests()
                .into_iter()
                .map(|request| request.dimensions)
                .collect()
        }

        fn requested_metadata(&self) -> Vec<ImageMetadata> {
            self.requests()
                .into_iter()
                .map(|request| request.metadata)
                .collect()
        }

        fn requested_sources(&self) -> Vec<Vec<u8>> {
            self.requests()
                .into_iter()
                .map(|request| request.source)
                .collect()
        }
    }

    impl MediaTierEncoder for FakeEncoder {
        fn encode_tier(
            &self,
            source: &[u8],
            metadata: ImageMetadata,
            dimensions: TierDimensions,
        ) -> Result<TierOutput, MosaicMediaError> {
            self.requests.borrow_mut().push(EncodeRequest {
                source: source.to_vec(),
                metadata,
                dimensions,
            });

            if let Some(error) = self.error.borrow_mut().take() {
                return Err(error);
            }

            let output_dimensions = self
                .output_override
                .borrow_mut()
                .take()
                .unwrap_or(dimensions);
            Ok(output(
                output_dimensions.tier,
                output_dimensions.width,
                output_dimensions.height,
                encoded_bytes(
                    output_dimensions.tier,
                    output_dimensions.width,
                    output_dimensions.height,
                ),
            ))
        }
    }

    fn encoded_bytes(tier: ShardTier, width: u32, height: u32) -> Vec<u8> {
        let mut bytes = b"encoded-tier:".to_vec();
        bytes.push(match tier {
            ShardTier::Thumbnail => b't',
            ShardTier::Preview => b'p',
            ShardTier::Original => b'o',
        });
        bytes.extend_from_slice(&width.to_be_bytes());
        bytes.extend_from_slice(&height.to_be_bytes());
        bytes
    }

    fn jpeg_segment(marker: u8, payload: &[u8]) -> Vec<u8> {
        let length = match u16::try_from(payload.len() + 2) {
            Ok(value) => value,
            Err(error) => panic!("test JPEG segment length should fit: {error:?}"),
        };
        let mut bytes = vec![0xff, marker];
        bytes.extend_from_slice(&length.to_be_bytes());
        bytes.extend_from_slice(payload);
        bytes
    }

    fn jpeg_with_segments(segments: &[Vec<u8>]) -> Vec<u8> {
        let mut bytes = vec![0xff, 0xd8];
        for segment in segments {
            bytes.extend_from_slice(segment);
        }
        bytes.extend_from_slice(&[0xff, 0xda, 0x00, 0x08, 1, 2, 3, 4, 5, 6]);
        bytes.extend_from_slice(b"scan bytes");
        bytes.extend_from_slice(&[0xff, 0xd9]);
        bytes
    }

    fn png_chunk(kind: [u8; 4], payload: &[u8]) -> Vec<u8> {
        let length = match u32::try_from(payload.len()) {
            Ok(value) => value,
            Err(error) => panic!("test PNG chunk length should fit: {error:?}"),
        };
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&length.to_be_bytes());
        bytes.extend_from_slice(&kind);
        bytes.extend_from_slice(payload);
        bytes.extend_from_slice(&[0, 0, 0, 0]);
        bytes
    }

    fn jpeg_sof_segment(marker: u8, height: u16, width: u16) -> Vec<u8> {
        let mut payload = vec![8];
        payload.extend_from_slice(&height.to_be_bytes());
        payload.extend_from_slice(&width.to_be_bytes());
        payload.extend_from_slice(&[3, 1, 0x11, 0, 2, 0x11, 0, 3, 0x11, 0]);
        jpeg_segment(marker, &payload)
    }

    fn jpeg_exif_orientation_segment(orientation: u16, little_endian: bool) -> Vec<u8> {
        let mut payload = b"Exif\0\0".to_vec();
        if little_endian {
            payload.extend_from_slice(b"II");
            payload.extend_from_slice(&42_u16.to_le_bytes());
            payload.extend_from_slice(&8_u32.to_le_bytes());
            payload.extend_from_slice(&1_u16.to_le_bytes());
            payload.extend_from_slice(&0x0112_u16.to_le_bytes());
            payload.extend_from_slice(&3_u16.to_le_bytes());
            payload.extend_from_slice(&1_u32.to_le_bytes());
            payload.extend_from_slice(&orientation.to_le_bytes());
            payload.extend_from_slice(&[0, 0]);
            payload.extend_from_slice(&0_u32.to_le_bytes());
        } else {
            payload.extend_from_slice(b"MM");
            payload.extend_from_slice(&42_u16.to_be_bytes());
            payload.extend_from_slice(&8_u32.to_be_bytes());
            payload.extend_from_slice(&1_u16.to_be_bytes());
            payload.extend_from_slice(&0x0112_u16.to_be_bytes());
            payload.extend_from_slice(&3_u16.to_be_bytes());
            payload.extend_from_slice(&1_u32.to_be_bytes());
            payload.extend_from_slice(&orientation.to_be_bytes());
            payload.extend_from_slice(&[0, 0]);
            payload.extend_from_slice(&0_u32.to_be_bytes());
        }

        jpeg_segment(0xe1, &payload)
    }

    fn jpeg_exif_segment(tiff_payload: &[u8]) -> Vec<u8> {
        let mut payload = b"Exif\0\0".to_vec();
        payload.extend_from_slice(tiff_payload);
        jpeg_segment(0xe1, &payload)
    }

    fn png_ihdr_chunk(width: u32, height: u32) -> Vec<u8> {
        let mut payload = Vec::new();
        payload.extend_from_slice(&width.to_be_bytes());
        payload.extend_from_slice(&height.to_be_bytes());
        payload.extend_from_slice(&[8, 2, 0, 0, 0]);
        png_chunk(*b"IHDR", &payload)
    }

    fn png_with_chunks(chunks: &[Vec<u8>]) -> Vec<u8> {
        let mut bytes = b"\x89PNG\r\n\x1a\n".to_vec();
        for chunk in chunks {
            bytes.extend_from_slice(chunk);
        }
        bytes
    }

    fn webp_chunk(kind: [u8; 4], payload: &[u8]) -> Vec<u8> {
        let length = match u32::try_from(payload.len()) {
            Ok(value) => value,
            Err(error) => panic!("test WebP chunk length should fit: {error:?}"),
        };
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&kind);
        bytes.extend_from_slice(&length.to_le_bytes());
        bytes.extend_from_slice(payload);
        if payload.len() % 2 == 1 {
            bytes.push(0);
        }
        bytes
    }

    fn webp_with_chunks(chunks: &[Vec<u8>]) -> Vec<u8> {
        let payload_len = chunks.iter().map(Vec::len).sum::<usize>() + 4;
        let riff_size = match u32::try_from(payload_len) {
            Ok(value) => value,
            Err(error) => panic!("test WebP RIFF size should fit: {error:?}"),
        };
        let mut bytes = b"RIFF".to_vec();
        bytes.extend_from_slice(&riff_size.to_le_bytes());
        bytes.extend_from_slice(b"WEBP");
        for chunk in chunks {
            bytes.extend_from_slice(chunk);
        }
        bytes
    }

    fn webp_vp8_chunk(width: u16, height: u16) -> Vec<u8> {
        let mut payload = vec![0x30, 0x01, 0x00, 0x9d, 0x01, 0x2a];
        payload.extend_from_slice(&(width & 0x3fff).to_le_bytes());
        payload.extend_from_slice(&(height & 0x3fff).to_le_bytes());
        payload.extend_from_slice(b"frame");
        webp_chunk(*b"VP8 ", &payload)
    }

    fn webp_vp8l_chunk(width: u32, height: u32) -> Vec<u8> {
        let width_minus_one = width - 1;
        let height_minus_one = height - 1;
        let bits = width_minus_one | (height_minus_one << 14);
        let mut payload = vec![0x2f];
        payload.extend_from_slice(&bits.to_le_bytes());
        webp_chunk(*b"VP8L", &payload)
    }

    fn webp_vp8x_chunk(width: u32, height: u32) -> Vec<u8> {
        let width_minus_one = width - 1;
        let height_minus_one = height - 1;
        let mut payload = vec![0; 10];
        payload[4..7].copy_from_slice(&width_minus_one.to_le_bytes()[..3]);
        payload[7..10].copy_from_slice(&height_minus_one.to_le_bytes()[..3]);
        webp_chunk(*b"VP8X", &payload)
    }

    fn contains_ascii(haystack: &[u8], needle: &[u8]) -> bool {
        haystack
            .windows(needle.len())
            .any(|candidate| candidate == needle)
    }
}
