// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mosaic.Backend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mosaic.Backend.Migrations
{
    [DbContext(typeof(MosaicDbContext))]
    [Migration("20251228062402_AddShareLinks")]
    partial class AddShareLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentEpochId")
                        .HasColumnType("integer")
                        .HasColumnName("current_epoch_id");

                    b.Property<long>("CurrentVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_albums");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_albums_owner_id");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumMember", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("AlbumId", "UserId")
                        .HasName("p_k_album_members");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("i_x_album_members_album_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("i_x_album_members_invited_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_album_members_user_id");

                    b.ToTable("album_members");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.EpochKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedKeyBundle")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_key_bundle");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<byte[]>("OwnerSignature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("owner_signature");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<byte[]>("SharerPubkey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sharer_pubkey");

                    b.Property<byte[]>("SignPubkey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sign_pubkey");

                    b.HasKey("Id")
                        .HasName("p_k_epoch_keys");

                    b.HasIndex("RecipientId", "AlbumId")
                        .HasDatabaseName("i_x_epoch_keys_recipient_id_album_id");

                    b.HasIndex("AlbumId", "RecipientId", "EpochId")
                        .IsUnique()
                        .HasDatabaseName("i_x_epoch_keys_album_id_recipient_id_epoch_id");

                    b.ToTable("epoch_keys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.LinkEpochKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<Guid>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.Property<byte[]>("WrappedNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_nonce");

                    b.HasKey("Id")
                        .HasName("p_k_link_epoch_keys");

                    b.HasIndex("ShareLinkId", "EpochId", "Tier")
                        .HasDatabaseName("i_x_link_epoch_keys_share_link_id_epoch_id_tier");

                    b.ToTable("link_epoch_keys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedMeta")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_meta");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<string>("SignerPubkey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signer_pubkey");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionCreated")
                        .HasColumnType("bigint")
                        .HasColumnName("version_created");

                    b.HasKey("Id")
                        .HasName("p_k_manifests");

                    b.HasIndex("AlbumId", "VersionCreated")
                        .HasDatabaseName("i_x_manifests_album_id_version_created");

                    b.ToTable("manifests");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ManifestShard", b =>
                {
                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<Guid>("ShardId")
                        .HasColumnType("uuid")
                        .HasColumnName("shard_id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.HasKey("ManifestId", "ShardId")
                        .HasName("p_k_manifest_shards");

                    b.HasIndex("ShardId")
                        .HasDatabaseName("i_x_manifest_shards_shard_id");

                    b.ToTable("manifest_shards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("PendingExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_expires_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("p_k_shards");

                    b.HasIndex("PendingExpiresAt")
                        .HasDatabaseName("i_x_shards_pending_expires_at")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("i_x_shards_uploader_id");

                    b.ToTable("shards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessTier")
                        .HasColumnType("integer")
                        .HasColumnName("access_tier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<byte[]>("LinkId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("link_id");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<byte[]>("OwnerEncryptedSecret")
                        .HasColumnType("bytea")
                        .HasColumnName("owner_encrypted_secret");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("p_k_share_links");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("i_x_share_links_album_id");

                    b.HasIndex("LinkId")
                        .IsUnique()
                        .HasDatabaseName("i_x_share_links_link_id");

                    b.ToTable("share_links");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthSub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_salt");

                    b.Property<string>("IdentityPubkey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_pubkey");

                    b.Property<byte[]>("SaltNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("salt_nonce");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("AuthSub")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_auth_sub");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.UserQuota", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("MaxStorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_storage_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UsedStorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("used_storage_bytes");

                    b.HasKey("UserId")
                        .HasName("p_k_user_quotas");

                    b.ToTable("user_quotas");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Owner")
                        .WithMany("OwnedAlbums")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_albums__users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumMember", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("Members")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_members_albums_album_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_album_members__users_invited_by");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_members__users_user_id");

                    b.Navigation("Album");

                    b.Navigation("Inviter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.EpochKey", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("EpochKeys")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_epoch_keys_albums_album_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Recipient")
                        .WithMany("EpochKeys")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_epoch_keys__users_recipient_id");

                    b.Navigation("Album");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.LinkEpochKey", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.ShareLink", "ShareLink")
                        .WithMany("LinkEpochKeys")
                        .HasForeignKey("ShareLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_link_epoch_keys__share_links_share_link_id");

                    b.Navigation("ShareLink");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("Manifests")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manifests_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ManifestShard", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Manifest", "Manifest")
                        .WithMany("ManifestShards")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manifest_shards_manifests_manifest_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.Shard", "Shard")
                        .WithMany("ManifestShards")
                        .HasForeignKey("ShardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_manifest_shards__shards_shard_id");

                    b.Navigation("Manifest");

                    b.Navigation("Shard");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_shards__users_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_share_links_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.UserQuota", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithOne("Quota")
                        .HasForeignKey("Mosaic.Backend.Data.Entities.UserQuota", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_quotas_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.Navigation("EpochKeys");

                    b.Navigation("Manifests");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.Navigation("ManifestShards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.Navigation("ManifestShards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.Navigation("LinkEpochKeys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.User", b =>
                {
                    b.Navigation("EpochKeys");

                    b.Navigation("Memberships");

                    b.Navigation("OwnedAlbums");

                    b.Navigation("Quota");
                });
#pragma warning restore 612, 618
        }
    }
}
