// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mosaic.Backend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mosaic.Backend.Migrations
{
    [DbContext(typeof(MosaicDbContext))]
    partial class MosaicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentEpochId")
                        .HasColumnType("integer")
                        .HasColumnName("current_epoch_id");

                    b.Property<long>("CurrentVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version");

                    b.Property<string>("EncryptedDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("encrypted_description");

                    b.Property<string>("EncryptedName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_name");

                    b.Property<int>("ExpirationWarningDays")
                        .HasColumnType("integer")
                        .HasColumnName("expiration_warning_days");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_albums");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_albums_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_albums_owner_id");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumContent", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_content");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AlbumId")
                        .HasName("p_k_album_contents");

                    b.ToTable("album_contents");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumLimits", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<int>("CurrentPhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_photo_count");

                    b.Property<long>("CurrentSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("current_size_bytes");

                    b.Property<int?>("MaxPhotos")
                        .HasColumnType("integer")
                        .HasColumnName("max_photos");

                    b.Property<long?>("MaxSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AlbumId")
                        .HasName("p_k_album_limits");

                    b.ToTable("album_limits");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumMember", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("AlbumId", "UserId")
                        .HasName("p_k_album_members");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("i_x_album_members_album_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("i_x_album_members_invited_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_album_members_user_id");

                    b.ToTable("album_members");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AuthChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Challenge")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("challenge");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_auth_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_auth_challenges_expires_at");

                    b.HasIndex("Username")
                        .HasDatabaseName("i_x_auth_challenges_username");

                    b.ToTable("auth_challenges");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.EpochKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedKeyBundle")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_key_bundle");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<byte[]>("OwnerSignature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("owner_signature");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<byte[]>("SharerPubkey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sharer_pubkey");

                    b.Property<byte[]>("SignPubkey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sign_pubkey");

                    b.HasKey("Id")
                        .HasName("p_k_epoch_keys");

                    b.HasIndex("RecipientId", "AlbumId")
                        .HasDatabaseName("i_x_epoch_keys_recipient_id_album_id");

                    b.HasIndex("AlbumId", "RecipientId", "EpochId")
                        .IsUnique()
                        .HasDatabaseName("i_x_epoch_keys_album_id_recipient_id_epoch_id");

                    b.ToTable("epoch_keys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.LinkEpochKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<Guid>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.Property<byte[]>("WrappedNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_nonce");

                    b.HasKey("Id")
                        .HasName("p_k_link_epoch_keys");

                    b.HasIndex("ShareLinkId", "EpochId", "Tier")
                        .HasDatabaseName("i_x_link_epoch_keys_share_link_id_epoch_id_tier");

                    b.ToTable("link_epoch_keys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Image")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedMeta")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_meta");

                    b.Property<byte[]>("EncryptedMetaSidecar")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_meta_sidecar");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("MetadataVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("metadata_version");

                    b.Property<int>("ProtocolVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("protocol_version");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signature");

                    b.Property<string>("SignerPubkey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signer_pubkey");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionCreated")
                        .HasColumnType("bigint")
                        .HasColumnName("version_created");

                    b.HasKey("Id")
                        .HasName("p_k_manifests");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_manifests_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("AlbumId", "VersionCreated")
                        .HasDatabaseName("i_x_manifests_album_id_version_created");

                    b.ToTable("manifests");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ManifestShard", b =>
                {
                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<Guid>("ShardId")
                        .HasColumnType("uuid")
                        .HasColumnName("shard_id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<long>("ContentLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("content_length");

                    b.Property<int>("EnvelopeVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("envelope_version");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("sha256");

                    b.Property<int>("ShardIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("shard_index");

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("tier");

                    b.HasKey("ManifestId", "ShardId")
                        .HasName("p_k_manifest_shards");

                    b.HasIndex("ShardId")
                        .HasDatabaseName("i_x_manifest_shards_shard_id");

                    b.ToTable("manifest_shards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_sessions_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_sessions_user_id");

                    b.HasIndex("TokenHash", "ExpiresAt")
                        .HasDatabaseName("i_x_sessions_token_hash_expires_at");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("PendingExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_expires_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("p_k_shards");

                    b.HasIndex("PendingExpiresAt")
                        .HasDatabaseName("i_x_shards_pending_expires_at")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("i_x_shards_uploader_id");

                    b.ToTable("shards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessTier")
                        .HasColumnType("integer")
                        .HasColumnName("access_tier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<byte[]>("LinkId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("link_id");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<byte[]>("OwnerEncryptedSecret")
                        .HasColumnType("bytea")
                        .HasColumnName("owner_encrypted_secret");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("p_k_share_links");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("i_x_share_links_album_id");

                    b.HasIndex("LinkId")
                        .IsUnique()
                        .HasDatabaseName("i_x_share_links_link_id");

                    b.ToTable("share_links");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLinkGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("GrantedUseCount")
                        .HasColumnType("integer")
                        .HasColumnName("granted_use_count");

                    b.Property<Guid>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("p_k_share_link_grants");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_share_link_grants_expires_at");

                    b.HasIndex("ShareLinkId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_share_link_grants_share_link_id_token_hash");

                    b.ToTable("share_link_grants");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("p_k_system_settings");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("i_x_system_settings_updated_by");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.TusUploadReservation", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_bytes");

                    b.Property<long>("UploadLength")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_length");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FileId")
                        .HasName("p_k_tus_upload_reservations");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("i_x_tus_upload_reservations_album_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("i_x_tus_upload_reservations_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_tus_upload_reservations_user_id");

                    b.ToTable("tus_upload_reservations");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccountSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("account_salt");

                    b.Property<string>("AuthPubkey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth_pubkey");

                    b.Property<string>("AuthSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth_sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_salt");

                    b.Property<string>("IdentityPubkey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("identity_pubkey");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<byte[]>("SaltNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("salt_nonce");

                    b.Property<byte[]>("UserSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("user_salt");

                    b.Property<byte[]>("WrappedAccountKey")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_account_key");

                    b.Property<byte[]>("WrappedIdentitySeed")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_identity_seed");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("AuthSub")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_auth_sub");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.UserQuota", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentAlbumCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_album_count");

                    b.Property<int?>("MaxAlbums")
                        .HasColumnType("integer")
                        .HasColumnName("max_albums");

                    b.Property<long>("MaxStorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_storage_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UsedStorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("used_storage_bytes");

                    b.HasKey("UserId")
                        .HasName("p_k_user_quotas");

                    b.ToTable("user_quotas");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Owner")
                        .WithMany("OwnedAlbums")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_albums__users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumContent", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithOne()
                        .HasForeignKey("Mosaic.Backend.Data.Entities.AlbumContent", "AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_contents_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumLimits", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithOne("Limits")
                        .HasForeignKey("Mosaic.Backend.Data.Entities.AlbumLimits", "AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_limits_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.AlbumMember", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("Members")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_members_albums_album_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_album_members__users_invited_by");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_album_members__users_user_id");

                    b.Navigation("Album");

                    b.Navigation("Inviter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.EpochKey", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("EpochKeys")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_epoch_keys_albums_album_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Recipient")
                        .WithMany("EpochKeys")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_epoch_keys__users_recipient_id");

                    b.Navigation("Album");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.LinkEpochKey", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.ShareLink", "ShareLink")
                        .WithMany("LinkEpochKeys")
                        .HasForeignKey("ShareLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_link_epoch_keys__share_links_share_link_id");

                    b.Navigation("ShareLink");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany("Manifests")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manifests_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ManifestShard", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Manifest", "Manifest")
                        .WithMany("ManifestShards")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manifest_shards_manifests_manifest_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.Shard", "Shard")
                        .WithMany("ManifestShards")
                        .HasForeignKey("ShardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_manifest_shards__shards_shard_id");

                    b.Navigation("Manifest");

                    b.Navigation("Shard");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Session", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sessions__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_shards__users_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_share_links_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLinkGrant", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.ShareLink", "ShareLink")
                        .WithMany("Grants")
                        .HasForeignKey("ShareLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_share_link_grants_share_links_share_link_id");

                    b.Navigation("ShareLink");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.SystemSetting", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_system_settings__users_updated_by");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.TusUploadReservation", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_tus_upload_reservations_albums_album_id");

                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tus_upload_reservations__users_user_id");

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.UserQuota", b =>
                {
                    b.HasOne("Mosaic.Backend.Data.Entities.User", "User")
                        .WithOne("Quota")
                        .HasForeignKey("Mosaic.Backend.Data.Entities.UserQuota", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_quotas_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Album", b =>
                {
                    b.Navigation("EpochKeys");

                    b.Navigation("Limits");

                    b.Navigation("Manifests");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Manifest", b =>
                {
                    b.Navigation("ManifestShards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.Shard", b =>
                {
                    b.Navigation("ManifestShards");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.ShareLink", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("LinkEpochKeys");
                });

            modelBuilder.Entity("Mosaic.Backend.Data.Entities.User", b =>
                {
                    b.Navigation("EpochKeys");

                    b.Navigation("Memberships");

                    b.Navigation("OwnedAlbums");

                    b.Navigation("Quota");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
