import type { PhotoMeta } from '../workers/types';

/**
 * Configuration for the mosaic layout
 */
export interface MosaicConfig {
  containerWidth: number;
  gap: number;
  targetRowHeight: number;
  minColWidth?: number;
}

/**
 * Types of tiles in the mosaic
 */
export type TileType = 'standard' | 'hero' | 'story' | 'map';

/**
 * A calculated item in the layout
 */
export interface MosaicItem {
  id: string; // Photo ID or special ID for non-photo blocks
  photoId?: string;
  type: TileType;
  rect: {
    top: number;
    left: number;
    width: number;
    height: number;
  };
  // Metadata used for rendering
  description?: string;
  isPortrait?: boolean;
}

/**
 * A row definition generated by the packer
 */
export interface RowDef {
  height: number;
  items: MosaicItem[];
  top?: number;
}

/**
 * Compute the mosaic layout for a flat list of photos
 */
export function computeMosaicLayout(
  photos: PhotoMeta[],
  config: MosaicConfig
): RowDef[] {
  const { containerWidth, gap, targetRowHeight } = config;
  const rows: RowDef[] = [];
  let currentTop = 0;

  // We process photos in batches to form "rows"
  let cursor = 0;
  
  while (cursor < photos.length) {
    // Look ahead to decide the next row template
    const remaining = photos.length - cursor;
    const currentPhoto = photos[cursor];
    if (!currentPhoto) break; 
    
    // Check if current photo has a long description -> Story Tile
    // Criteria: Description exists and is longer than 20 chars
    const hasStory = !!currentPhoto.description && currentPhoto.description.length > 20;
    
    // Check next few photos for shape
    const p1 = currentPhoto;
    const p2 = photos[cursor + 1];
    const p3 = photos[cursor + 2];
    
    let row: RowDef;

    if (hasStory) {
      // TEMPLATE: Story Row
      row = createStoryRow(p1, containerWidth, targetRowHeight * 1.5, gap, currentTop);
      cursor += 1;
    } 
    else if (remaining >= 3 && p1 && p2 && p3 && isPortrait(p1) && !isPortrait(p2) && !isPortrait(p3)) {
      // TEMPLATE: Portrait Focus (Left)
      row = createHeroLeftRow([p1, p2, p3], containerWidth, targetRowHeight * 2, gap, currentTop);
      cursor += 3;
    }
    else if (remaining >= 2 && p1 && p2 && isPortrait(p1) && isPortrait(p2)) {
      // TEMPLATE: Dual Portrait
      row = createDualPortraitRow([p1, p2], containerWidth, targetRowHeight * 1.5, gap, currentTop);
      cursor += 2;
    }
    else {
      // DEFAULT: Justified Row (fallback)
      const count = Math.min(remaining, 3);
      const rowPhotos = photos.slice(cursor, cursor + count);
      row = createStandardRow(rowPhotos, containerWidth, targetRowHeight, gap, currentTop);
      cursor += count;
    }

    row.top = currentTop;
    rows.push(row);
    currentTop += row.height + gap;
  }

  return rows;
}


// --- Helper Functions to Create Rows ---

function isPortrait(p: PhotoMeta): boolean {
  if (!p || !p.width || !p.height) return false;
  return p.height > p.width;
}

function createStoryRow(
  photo: PhotoMeta,
  width: number,
  height: number,
  _gap: number,
  top: number
): RowDef {
  return {
    height,
    items: [
      {
        id: photo.id,
        photoId: photo.id,
        type: 'story',
        description: photo.description || '', // Ensure string
        rect: { top, left: 0, width, height }
      }
    ]
  };
}

function createHeroLeftRow(
  photos: PhotoMeta[], // Expects [Portrait, Landscape, Landscape]
  width: number,
  height: number,
  gap: number,
  top: number
): RowDef {
  const col2Width = (width - gap) / 3;
  const col1Width = width - col2Width - gap;
  const halfHeight = (height - gap) / 2;

  const [p1, p2, p3] = photos;
  if (!p1 || !p2 || !p3) return { height: 0, items: [] }; // Safety

  return {
    height,
    items: [
      {
        id: p1.id,
        photoId: p1.id,
        type: 'hero',
        rect: { top, left: 0, width: col1Width, height }
      },
      {
        id: p2.id,
        photoId: p2.id,
        type: 'standard',
        rect: { top, left: col1Width + gap, width: col2Width, height: halfHeight }
      },
      {
        id: p3.id,
        photoId: p3.id,
        type: 'standard',
        rect: { top: top + halfHeight + gap, left: col1Width + gap, width: col2Width, height: halfHeight }
      }
    ]
  };
}

function createDualPortraitRow(
  photos: PhotoMeta[],
  width: number,
  height: number,
  gap: number,
  top: number
): RowDef {
  const itemWidth = (width - gap) / 2;
  return {
    height,
    items: photos.map((p, i) => ({
      id: p.id,
      photoId: p.id,
      type: 'standard', 
      isPortrait: true,
      rect: {
        top,
        left: i * (itemWidth + gap),
        width: itemWidth,
        height
      }
    }))
  };
}

function createStandardRow(
  photos: PhotoMeta[],
  width: number,
  targetHeight: number,
  gap: number,
  top: number
): RowDef {
  // Simple aspect ratio packing
  const ratios = photos.map(p => (p.width && p.height) ? p.width / p.height : 1);
  const totalRatio = ratios.reduce((sum, r) => sum + r, 0);
  
  const totalGap = (photos.length - 1) * gap;
  const height = totalRatio > 0 ? (width - totalGap) / totalRatio : targetHeight;
  
  let currentLeft = 0;
  const items: MosaicItem[] = photos.map((p, i) => {
    const r = ratios[i]!;
    const itemWidth = height * r;
    const item = {
      id: p.id,
      photoId: p.id,
      type: 'standard',
      rect: {
        top,
        left: currentLeft,
        width: itemWidth, 
        height
      }
    } as MosaicItem;
    currentLeft += itemWidth + gap;
    return item;
  });

  return { height, items };
}
